import * as THREE from 'three';
import { CastleJesterGatekeeper } from './castle_jester_gatekeeper.js';

const modelUrl=new URL('../assets/assets/models/castle_jester_rigged.glb',document.baseURI).href;
const MOVE_SLOP_PX=9;
document.body.dataset.castleJesterAsset=modelUrl;
document.body.dataset.castleEntranceTrigger='rigged-jester-single-click';
document.body.dataset.castleJesterIntegration='waiting-for-runtime';
let gatekeeper=null,frame=0,previousTime=performance.now(),pointerDown=null,activeRuntime=null,interiorFocusFrame=0;
function isWorldVisible(object){for(let current=object;current;current=current.parent){if(current.visible===false)return false}return true}
function labelFor(object){const materials=Array.isArray(object.material)?object.material:[object.material];return [object.name,...materials.filter(Boolean).map(material=>material.name)].filter(Boolean).join(' ').toLowerCase()}
function findConstructionPanel(runtime){const camera=runtime?.camera,scene=runtime?.scene;if(!camera||!scene)return null;camera.updateMatrixWorld(true);const keyword=/construction|panel|sign|dupuis|exhibition|preparation|préparation/;let named=null,namedScore=-Infinity,geometric=null,geometricScore=-Infinity;const box=new THREE.Box3(),size=new THREE.Vector3(),center=new THREE.Vector3();scene.traverse(object=>{if(!object.isMesh||!isWorldVisible(object))return;box.setFromObject(object);if(box.isEmpty())return;box.getSize(size);box.getCenter(center);const dims=[Math.abs(size.x),Math.abs(size.y),Math.abs(size.z)].sort((a,b)=>a-b),thin=dims[0],mid=dims[1],long=dims[2];if(long<.45||mid<.28)return;const projected=center.clone().project(camera);if(projected.z<-1.2||projected.z>1.2||Math.abs(projected.x)>1.35||Math.abs(projected.y)>1.35)return;const distance=camera.position.distanceTo(center),screenPenalty=Math.hypot(projected.x,projected.y*.8),label=labelFor(object);if(keyword.test(label)){const score=1000-distance*2-screenPenalty*20+Math.min(long*mid,30);if(score>namedScore){namedScore=score;named={object,center:center.clone(),size:size.clone(),label}}return}const flatness=thin/Math.max(mid,.001),ratio=long/Math.max(mid,.001);if(flatness>.34||ratio<1.15||ratio>4.8||long>14||mid>8)return;const score=120-distance*2.4-screenPenalty*28-flatness*35-Math.abs(ratio-1.9)*5;if(score>geometricScore){geometricScore=score;geometric={object,center:center.clone(),size:size.clone(),label}}});return named||geometric}
function focusInteriorOnConstructionPanel(runtime){if(!runtime?.camera)return false;const match=findConstructionPanel(runtime);let target;if(match){target=match.center.clone();target.y+=Math.max(.15,Math.min(match.size.y*.08,.55));document.body.dataset.castleInteriorEntryTarget=match.label||match.object.name||'construction-panel-geometry'}else{target=new THREE.Vector3(-3.6,2.8,5);document.body.dataset.castleInteriorEntryTarget='construction-panel-fallback'}if(runtime.orbit?.target){runtime.orbit.target.copy(target);runtime.updateOrbit?.()}else runtime.camera.lookAt(target);document.body.dataset.castleInteriorEntryCamera='construction-panel-v1';return true}
function armInteriorEntryFocus(runtime){if(interiorFocusFrame)cancelAnimationFrame(interiorFocusFrame);let attempts=0;const apply=()=>{if(document.body.dataset.sceneMode==='interior'){focusInteriorOnConstructionPanel(runtime);interiorFocusFrame=0;return}if(attempts++<1200)interiorFocusFrame=requestAnimationFrame(apply);else interiorFocusFrame=0};interiorFocusFrame=requestAnimationFrame(apply)}
function requestEntrance(){if(document.body.dataset.sceneMode==='interior')return;document.body.dataset.castleJesterState='opening-gate';armInteriorEntryFocus(activeRuntime);window.dispatchEvent(new CustomEvent('castleJesterEnter'))}
function alignCastleToPlaza(castleRoot){if(!castleRoot||castleRoot.userData.unoPlazaAligned)return;castleRoot.rotation.y+=Math.PI;castleRoot.updateMatrixWorld(true);castleRoot.userData.unoPlazaAligned=true;document.body.dataset.castleExteriorAlignment='gate-to-uno-plaza-180deg-v17'}
function placeAtGate(castleRoot,camera){if(!gatekeeper||!castleRoot||gatekeeper.clicked)return;alignCastleToPlaza(castleRoot);const box=new THREE.Box3().setFromObject(castleRoot);if(box.isEmpty())return;const size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());gatekeeper.root.position.set(center.x,box.min.y+.04,box.max.z+Math.max(1.05,size.z*.038));if(camera){const cameraWorld=new THREE.Vector3();camera.getWorldPosition(cameraWorld);const dx=cameraWorld.x-gatekeeper.root.position.x,dz=cameraWorld.z-gatekeeper.root.position.z;gatekeeper.root.rotation.y=Math.atan2(dx,dz)}else gatekeeper.root.rotation.y=Math.PI;document.body.dataset.castleJesterPlacement='rotated-front-gate-facing-camera-v17';document.body.dataset.castleJesterGatePosition=[gatekeeper.root.position.x.toFixed(2),gatekeeper.root.position.y.toFixed(2),gatekeeper.root.position.z.toFixed(2)].join(',')}
function stop(event){event.preventDefault();event.stopImmediatePropagation()}
function activateSingleClick(event,canvas){if(!gatekeeper?.hitTest(event))return false;document.body.dataset.castleJesterGesture='single-click';if(!gatekeeper.click(event))return false;gatekeeper.enterDispatched=true;gatekeeper.clearHover();canvas.style.cursor='';requestEntrance();return true}
function installPointerHandlers(canvas){if(canvas.dataset.castleJesterPointerHandlers==='true')return;canvas.dataset.castleJesterPointerHandlers='true';canvas.addEventListener('pointerdown',event=>{if(document.body.dataset.sceneMode==='interior')return;const jester=gatekeeper?.hitTest(event)===true;pointerDown={pointerId:event.pointerId,x:event.clientX,y:event.clientY,jester,moved:false};if(jester){stop(event);canvas.style.cursor='pointer'}},true);canvas.addEventListener('pointermove',event=>{if(document.body.dataset.sceneMode==='interior')return;if(pointerDown&&pointerDown.pointerId===event.pointerId){if(Math.hypot(event.clientX-pointerDown.x,event.clientY-pointerDown.y)>MOVE_SLOP_PX)pointerDown.moved=true;if(pointerDown.jester){stop(event);return}}const hover=gatekeeper?.setHover(event)===true;canvas.style.cursor=hover?'pointer':''},true);canvas.addEventListener('pointerup',event=>{if(document.body.dataset.sceneMode==='interior'){pointerDown=null;return}const down=pointerDown;pointerDown=null;if(!down||down.pointerId!==event.pointerId||!down.jester||down.moved)return;if(activateSingleClick(event,canvas))stop(event)},true);canvas.addEventListener('pointercancel',()=>{pointerDown=null;gatekeeper?.clearHover();canvas.style.cursor=''},true);canvas.addEventListener('pointerleave',()=>{if(!pointerDown){gatekeeper?.clearHover();canvas.style.cursor=''}},true);canvas.addEventListener('click',event=>{if(document.body.dataset.sceneMode==='interior')return;if(activateSingleClick(event,canvas))stop(event)},true)}
function animate(now){const delta=Math.min(.05,Math.max(0,(now-previousTime)/1000));previousTime=now;if(gatekeeper){if(document.body.dataset.sceneMode!=='interior'&&!gatekeeper.clicked)placeAtGate(activeRuntime?.castleRoot,activeRuntime?.camera);gatekeeper.setVisible(document.body.dataset.sceneMode!=='interior');gatekeeper.update(delta)}frame=requestAnimationFrame(animate)}
function install(runtime){if(!runtime?.scene||!runtime?.camera||!runtime?.renderer)return;activeRuntime=runtime;alignCastleToPlaza(runtime.castleRoot);if(gatekeeper)gatekeeper.dispose();gatekeeper=new CastleJesterGatekeeper({scene:runtime.scene,camera:runtime.camera,renderer:runtime.renderer,onEnterRequested:requestEntrance,modelUrl});installPointerHandlers(runtime.renderer.domElement);document.body.dataset.castleJesterIntegration='active';if(!frame){previousTime=performance.now();frame=requestAnimationFrame(animate)}}
function tryInstall(){const runtime=window.__castleSearchRuntime;if(runtime){install(runtime);return true}return false}
window.addEventListener('castleRuntimeReady',()=>tryInstall(),{passive:true});if(!tryInstall()){let attempts=0;const timer=setInterval(()=>{if(tryInstall()||attempts++>160)clearInterval(timer)},100)}
window.addEventListener('beforeunload',()=>{if(frame)cancelAnimationFrame(frame);if(interiorFocusFrame)cancelAnimationFrame(interiorFocusFrame);gatekeeper?.dispose()},{once:true});
