const LOADER_ART_URL=new URL('../assets/assets/images/castle_jester_loading_bar.png',document.baseURI).href;
if(!window.__castleSharedTransitionLoaderV68Installed){
 window.__castleSharedTransitionLoaderV68Installed=true;let timer=0,value=0,targetMode='',startedAt=0,finishing=false,suppressUntil=0;
 function ensure(){let root=document.getElementById('castle-shared-transition-loader');if(root)return root;const style=document.createElement('style');style.textContent=`#castle-shared-transition-loader{position:fixed;inset:0;z-index:2147483647;display:grid;place-items:center;background:radial-gradient(circle at 50% 44%,rgba(66,6,5,.42),rgba(2,6,11,.96) 58%,#02060b);opacity:0;visibility:hidden;pointer-events:none;transition:opacity .22s ease,visibility .22s ease}#castle-shared-transition-loader.is-visible{opacity:1;visibility:visible;pointer-events:auto}.scene-loader-shell{width:min(96vw,1280px);text-align:center;padding:18px}.scene-loader-art{position:relative;width:100%;aspect-ratio:3/1;margin:auto;filter:drop-shadow(0 18px 30px rgba(0,0,0,.7))}.scene-loader-base{position:absolute;inset:0;background:url('${LOADER_ART_URL}') center/contain no-repeat;filter:brightness(.5) saturate(.68)}.scene-loader-track{position:absolute;left:8.55%;right:8.55%;top:44.15%;height:8.15%;border-radius:999px;overflow:hidden;z-index:2;box-shadow:inset 0 0 9px rgba(0,0,0,.88)}.scene-loader-fill{position:absolute;inset:0 auto 0 0;width:0;border-radius:999px;background:repeating-linear-gradient(90deg,#66100d 0 18px,#9d1a11 18px 36px,#d43217 36px 54px,#ff7d2d 54px 72px);box-shadow:inset 0 0 14px rgba(255,175,70,.72),0 0 12px rgba(255,64,18,.48);transition:width .22s ease}.scene-loader-percent{margin-top:8px;color:#e8b660;font:600 clamp(26px,4vw,44px)/1.1 Georgia,serif;text-shadow:0 2px 12px rgba(0,0,0,.8)}.scene-loader-stage{margin-top:8px;color:#d7c8b0;font:600 clamp(13px,2vw,18px)/1.2 Georgia,serif;letter-spacing:.18em;text-transform:uppercase}@media(max-width:700px){.scene-loader-shell{width:96vw;padding:8px}.scene-loader-track{left:8.55%;right:8.55%;top:44.15%;height:8.15%}.scene-loader-percent{margin-top:2px;font-size:clamp(24px,8vw,34px)}.scene-loader-stage{font-size:clamp(12px,3.6vw,16px);letter-spacing:.12em}}`;document.head.append(style);root=document.createElement('div');root.id='castle-shared-transition-loader';root.innerHTML='<div class="scene-loader-shell"><div class="scene-loader-art"><div class="scene-loader-base"></div><div class="scene-loader-track"><div class="scene-loader-fill"></div></div></div><div class="scene-loader-percent">0%</div><div class="scene-loader-stage">INITIALISATION</div></div>';document.body.append(root);return root;}
 function progress(v){const root=ensure();value=Math.max(0,Math.min(100,v));root.querySelector('.scene-loader-fill').style.width=value+'%';root.querySelector('.scene-loader-percent').textContent=Math.round(value)+'%';}
 function stage(text){const node=ensure().querySelector('.scene-loader-stage');if(node)node.textContent=text||'LOADING';}
 function suppressEntrance(){if(performance.now()>suppressUntil)return;const transition=document.getElementById('castle-entrance-transition'),video=document.getElementById('castle-entrance-video'),label=document.getElementById('castle-interior-loading-label');try{video?.pause?.()}catch(_){}document.body.classList.remove('entrance-video-active');transition?.setAttribute('aria-hidden','true');if(label)label.style.display='none';setTimeout(suppressEntrance,80);}
 function hide(){const root=document.getElementById('castle-shared-transition-loader');if(!root)return;clearInterval(timer);progress(100);stage('READY');root.style.pointerEvents='none';setTimeout(()=>{root.classList.remove('is-visible');document.body.dataset.castleSharedLoader='hidden-v68';targetMode='';finishing=false;},280);}
 function complete(reason){if(finishing)return;finishing=true;document.body.dataset.castleTransitionTerminal=reason||'ready-v72';progress(100);hide();}
 function fail(reason){if(finishing)return;finishing=true;clearInterval(timer);document.body.dataset.castleTransitionTerminal=reason||'retry-v68';stage('RETRY');setTimeout(()=>{const root=document.getElementById('castle-shared-transition-loader');if(root)root.style.pointerEvents='none';root?.classList.remove('is-visible');document.body.dataset.castleSharedLoader='retry-v68';targetMode='';finishing=false;},700);}
 function sync(){if(!targetMode||finishing)return;const body=document.body,mode=body.dataset.sceneMode||'exterior';if(targetMode==='interior'){if(mode==='interior'){complete('interior-visible-v68');return;}if(body.dataset.interiorReady==='true'){progress(Math.max(value,96));document.body.dataset.castleTransitionTerminal='interior-ready-awaiting-video-v72';}if(body.dataset.interiorReady==='false'&&Date.now()-startedAt>500){fail('interior-retry-v74');return;}}else if(targetMode==='laboratory'){if(mode==='laboratory'){complete('laboratory-visible-v68');return;}if(body.dataset.laboratoryReady==='true')progress(Math.max(value,96));if(body.dataset.laboratoryReady==='false'&&Date.now()-startedAt>500){fail('laboratory-retry-v68');return;}}if(Date.now()-startedAt>35000)fail(targetMode+'-timeout-v68');}
 function show(label){const root=ensure();clearInterval(timer);finishing=false;value=0;startedAt=Date.now();targetMode=/LABORATORY/i.test(label||'')?'laboratory':/INTERIOR/i.test(label||'')?'interior':'';progress(3);stage(label||'LOADING');root.style.pointerEvents='auto';root.classList.add('is-visible');timer=setInterval(()=>{if(value<90)progress(value+Math.max(.8,(92-value)*.07));sync();},180);document.body.dataset.castleSharedLoader='visible-v68';sync();}
 window.__castleShowSceneLoader=show;window.__castleSetSceneLoaderProgress=progress;window.__castleHideSceneLoader=hide;
 window.addEventListener('castleJesterEnter',()=>show('INTERIOR LOADING'),true);
 const observer=new MutationObserver(sync);observer.observe(document.body,{attributes:true,attributeFilter:['data-scene-mode','data-interior-ready','data-laboratory-ready','data-ios-laboratory-stage']});
}
