import * as THREE from 'three';

if (!window.__castleLaboratoryMedallionButtonInstalled) {
  window.__castleLaboratoryMedallionButtonInstalled = true;
  const host=document.createElement('button');host.id='laboratory-medallion-button';host.type='button';host.setAttribute('aria-label','Entrer dans le laboratoire');host.title='Entrer dans le laboratoire';host.innerHTML='<span class="lab-medallion-canvas" aria-hidden="true"></span>';document.body.appendChild(host);
  const style=document.createElement('style');style.textContent=`#laboratory-medallion-button{position:fixed;left:50%;bottom:max(18px,env(safe-area-inset-bottom));transform:translateX(-50%);z-index:2147483000;width:126px;height:132px;padding:0;border:0;background:transparent;cursor:pointer;display:none;place-items:center;pointer-events:auto;-webkit-tap-highlight-color:transparent;filter:drop-shadow(0 9px 14px rgba(0,0,0,.72))}body[data-scene-mode="interior"] #laboratory-medallion-button{display:grid}body[data-scene-mode="laboratory"] #laboratory-medallion-button,body[data-scene-mode="exterior"] #laboratory-medallion-button{display:none}#laboratory-medallion-button .lab-medallion-canvas{width:116px;height:128px;display:block;position:relative}#laboratory-medallion-button canvas{display:block;width:116px!important;height:128px!important;pointer-events:none}@media(max-width:700px){#laboratory-medallion-button{width:104px;height:108px;bottom:max(12px,env(safe-area-inset-bottom))}#laboratory-medallion-button .lab-medallion-canvas,#laboratory-medallion-button canvas{width:96px!important;height:106px!important}}`;document.head.appendChild(style);
  const mount=host.querySelector('.lab-medallion-canvas'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(30,116/128,.1,20);camera.position.set(0,.02,5.6);let renderer=null;try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.5));renderer.setSize(116,128,false);renderer.setClearColor(0x000000,0);renderer.outputColorSpace=THREE.SRGBColorSpace;mount.appendChild(renderer.domElement)}catch(_){host.classList.add('lab-medallion-renderer-failed')}
  scene.add(new THREE.HemisphereLight(0xdce8f0,0x10161b,1.55));const key=new THREE.DirectionalLight(0xffffff,2.4);key.position.set(3.5,4.5,5);scene.add(key);
  function buildMedallion(){const shape=new THREE.Shape();shape.moveTo(-.79,-.86);shape.bezierCurveTo(-1.02,-.55,-1.05,-.08,-.94,.34);shape.bezierCurveTo(-.80,.83,-.48,1.09,-.30,1.27);shape.bezierCurveTo(-.18,1.39,-.16,1.58,-.15,1.82);shape.bezierCurveTo(-.14,2.04,.14,2.04,.15,1.82);shape.bezierCurveTo(.16,1.58,.18,1.39,.30,1.27);shape.bezierCurveTo(.48,1.09,.80,.83,.94,.34);shape.bezierCurveTo(1.05,-.08,1.02,-.55,.79,-.86);shape.bezierCurveTo(.57,-1.15,.30,-1.28,0,-1.30);shape.bezierCurveTo(-.30,-1.28,-.57,-1.15,-.79,-.86);shape.closePath();const hole=new THREE.Path();hole.absellipse(0,1.69,.12,.12,0,Math.PI*2,false,0);shape.holes.push(hole);const geometry=new THREE.ExtrudeGeometry(shape,{depth:.105,bevelEnabled:true,bevelThickness:.025,bevelSize:.022,bevelSegments:2,curveSegments:20,steps:1});geometry.center();const mesh=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color:0x555b5f,metalness:.91,roughness:.34}));mesh.scale.setScalar(.86);const group=new THREE.Group();group.add(mesh);group.position.y=-.10;return group}
  const medallion=buildMedallion();scene.add(medallion);const clock=new THREE.Clock();function render(){requestAnimationFrame(render);if(!renderer||document.hidden||document.body.dataset.sceneMode!=='interior')return;medallion.rotation.set(0,clock.getElapsedTime()*.82,0);renderer.render(scene,camera)}render();
  function sync(){const interior=document.body.dataset.sceneMode==='interior';host.disabled=!interior||document.body.dataset.laboratoryReady==='loading';host.setAttribute('aria-busy',document.body.dataset.laboratoryReady==='loading'?'true':'false')}
  function primeVideo(){if(document.body.dataset.sceneMode!=='interior')return;document.body.dataset.bureauVideoGestureSource='laboratory-medallion-v84';window.__castleBureauVideoPrime?.()}
  host.addEventListener('pointerdown',primeVideo,{passive:true});host.addEventListener('touchstart',primeVideo,{passive:true});host.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();if(document.body.dataset.sceneMode!=='interior')return;primeVideo();window.__castleShowSceneLoader?.('LABORATORY LOADING');if(typeof window.__castleOpenLaboratory==='function'){void window.__castleOpenLaboratory();return}window.dispatchEvent(new CustomEvent('castle-open-laboratory'))});
  new MutationObserver(sync).observe(document.body,{attributes:true,attributeFilter:['data-scene-mode','data-laboratory-ready']});sync();document.body.dataset.laboratoryMedallionLabel='removed-v84';
}
