import * as THREE from 'three';
import { GLTFLoader } from '../vendor/GLTFLoader.js';

const isIOS = /iP(?:hone|ad|od)/.test(navigator.userAgent || '') ||
  (navigator.platform === 'MacIntel' && navigator.maxTouchPoints > 1);

if (isIOS && !window.__castleIOSLaboratoryResilienceV62Installed) {
  window.__castleIOSLaboratoryResilienceV62Installed = true;

  const LABORATORY_URL = new URL('../assets/assets/models/laboratory_interior.glb', document.baseURI).href;
  const LOADER_ART_URL = new URL('../assets/assets/images/castle_jester_loading_bar.png', document.baseURI).href;
  const LABORATORY_TARGET_SPAN = 50;
  const FETCH_TIMEOUT_MS = 16000;
  const PARSE_TIMEOUT_MS = 14000;
  let runtime=null,laboratoryRoot=null,laboratoryBounds=null,laboratoryBytes=null,laboratoryBytesPromise=null,laboratoryRootPromise=null,entryPromise=null,warmTimer=0,warmupFailed=false,activeFetchController=null;
  document.body.dataset.iosLaboratoryOwner='ios-resilience-v63';
  document.body.dataset.iosLaboratoryAsset=LABORATORY_URL;
  const mode=()=>document.body.dataset.sceneMode||'exterior';
  function refreshRuntime(){runtime=window.__castleSearchRuntime||runtime;return runtime}
  function publishSceneState(nextMode){document.body.dataset.sceneMode=nextMode;document.body.dataset.castleNavigationScene=nextMode;document.body.dataset.castleSubscene=nextMode==='laboratory'?'laboratory':''}
  function findCardGroup(){return runtime?.scene?.children?.find(child=>child?.isGroup&&child.children?.some(item=>item?.userData?.card))||null}
  function withTimeout(promise,timeoutMs,code){let timer=0;const timeout=new Promise((_,reject)=>{timer=setTimeout(()=>{const error=new Error(code);error.code=code;reject(error)},timeoutMs)});return Promise.race([promise,timeout]).finally(()=>clearTimeout(timer))}

  function ensureTransitionLoader(){
    let root=document.getElementById('castle-scene-transition-loader');
    if(root)return root;
    const style=document.createElement('style');style.id='castle-scene-transition-loader-style';style.textContent=`#castle-scene-transition-loader{position:fixed;inset:0;z-index:2147483100;display:none;place-items:center;background:radial-gradient(circle at 50% 44%,rgba(66,6,5,.42),rgba(2,6,11,.96) 58%,#02060b);opacity:0;transition:opacity .18s ease;pointer-events:auto}#castle-scene-transition-loader.is-visible{display:grid;opacity:1}.castle-scene-loader-shell{width:min(96vw,1280px);text-align:center;padding:18px}.castle-scene-loader-art{position:relative;width:100%;aspect-ratio:3/1;background:url('${LOADER_ART_URL}') center/contain no-repeat;filter:drop-shadow(0 18px 30px rgba(0,0,0,.7)) brightness(.72)}.castle-scene-loader-stage{margin-top:8px;color:#d7c8b0;font:600 clamp(13px,2vw,18px)/1.2 Georgia,serif;letter-spacing:.18em;text-transform:uppercase}@media(max-width:700px){.castle-scene-loader-shell{width:96vw;padding:8px}.castle-scene-loader-stage{font-size:clamp(12px,3.6vw,16px);letter-spacing:.12em}}`;
    document.head.append(style);root=document.createElement('div');root.id='castle-scene-transition-loader';root.setAttribute('aria-live','polite');root.innerHTML='<div class="castle-scene-loader-shell"><div class="castle-scene-loader-art"></div><div class="castle-scene-loader-stage">LABORATORY LOADING</div></div>';document.body.append(root);return root;
  }
  function showTransitionLoader(label='LABORATORY LOADING'){const root=ensureTransitionLoader();const stage=root.querySelector('.castle-scene-loader-stage');if(stage)stage.textContent=label;root.classList.add('is-visible');document.body.dataset.castleSceneLoading='laboratory'}
  function hideTransitionLoader(){const root=document.getElementById('castle-scene-transition-loader');root?.classList.remove('is-visible');delete document.body.dataset.castleSceneLoading}

  async function fetchLaboratoryBytes({reload=false,silent=false}={}){if(laboratoryBytes)return laboratoryBytes;if(laboratoryBytesPromise)return laboratoryBytesPromise;const controller=new AbortController();activeFetchController=controller;const timeout=setTimeout(()=>controller.abort('laboratory-fetch-timeout'),FETCH_TIMEOUT_MS);if(!silent)document.body.dataset.iosLaboratoryStage='fetching-v63';else document.body.dataset.iosLaboratoryWarmup='fetching-v63';laboratoryBytesPromise=fetch(LABORATORY_URL,{cache:reload?'reload':'force-cache',signal:controller.signal}).then(response=>{if(!response.ok)throw new Error(`laboratory-http-${response.status}`);return response.arrayBuffer()}).then(buffer=>{if(!buffer?.byteLength)throw new Error('laboratory-empty-response');laboratoryBytes=buffer;warmupFailed=false;document.body.dataset.iosLaboratoryBytes=String(buffer.byteLength);document.body.dataset.iosLaboratoryWarmup='ready-v63';return buffer}).catch(error=>{laboratoryBytes=null;warmupFailed=true;document.body.dataset.iosLaboratoryWarmup='failed-v63';document.body.dataset.iosLaboratoryWarmupError=String(error?.message||error);throw error}).finally(()=>{clearTimeout(timeout);if(activeFetchController===controller)activeFetchController=null;laboratoryBytesPromise=null});return laboratoryBytesPromise}
  function createLaboratoryLoader(){const loader=new GLTFLoader();let draco=null;const SharedDRACOLoader=window.DRACOLoader,shared=window.__castleSharedDraco;if(typeof SharedDRACOLoader==='function'&&shared){draco=new SharedDRACOLoader();draco.setDecoderPath(shared.decoderPath);draco.setDecoderConfig({type:shared.decoderType||'js'});draco.setWorkerLimit(1);draco.preload();loader.setDRACOLoader(draco);document.body.dataset.iosLaboratoryDraco=`${shared.decoderType||'js'}-worker-1-v63`}return{loader,draco}}
  async function parseLaboratory(buffer){const{loader,draco}=createLaboratoryLoader();const basePath=new URL('.',LABORATORY_URL).href;document.body.dataset.iosLaboratoryStage='decoding-v63';try{return (await withTimeout(loader.parseAsync(buffer,basePath),PARSE_TIMEOUT_MS,'laboratory-decode-timeout')).scene}finally{draco?.dispose?.()}}
  function normalizeLaboratory(root){root.updateMatrixWorld(true);let bounds=new THREE.Box3().setFromObject(root);const size=bounds.getSize(new THREE.Vector3()),horizontalSpan=Math.max(size.x,size.z,.001),scale=LABORATORY_TARGET_SPAN/horizontalSpan;root.scale.multiplyScalar(scale);root.updateMatrixWorld(true);bounds=new THREE.Box3().setFromObject(root);const center=bounds.getCenter(new THREE.Vector3());root.position.x-=center.x;root.position.y-=bounds.min.y;root.position.z-=center.z;root.updateMatrixWorld(true);laboratoryBounds=new THREE.Box3().setFromObject(root);root.userData.laboratoryNormalized=true;root.userData.laboratoryNormalizationScale=scale;document.body.dataset.laboratoryNormalization='ios-resilient-center-floor-v63'}
  async function ensureLaboratoryRoot(){refreshRuntime();if(laboratoryRoot)return laboratoryRoot;if(!runtime?.scene)throw new Error('laboratory-runtime-unavailable');if(laboratoryRootPromise)return laboratoryRootPromise;laboratoryRootPromise=(async()=>{const buffer=await fetchLaboratoryBytes({reload:warmupFailed});const root=await parseLaboratory(buffer);root.name='BureauOfAI';root.visible=false;normalizeLaboratory(root);runtime.scene.add(root);laboratoryRoot=root;laboratoryBytes=null;document.body.dataset.laboratoryReady='true';document.body.dataset.iosLaboratoryStage='ready-v63';delete document.body.dataset.laboratoryError;delete document.body.dataset.iosLaboratoryError;return root})().catch(error=>{laboratoryBytes=null;warmupFailed=true;document.body.dataset.laboratoryReady='false';document.body.dataset.iosLaboratoryStage='failed-v63';document.body.dataset.iosLaboratoryError=String(error?.message||error);document.body.dataset.laboratoryError=String(error?.message||error);throw error}).finally(()=>{if(!laboratoryRoot)laboratoryRootPromise=null});return laboratoryRootPromise}
  function setLaboratoryStartingView(){if(!runtime?.orbit||!laboratoryRoot)return;laboratoryBounds=new THREE.Box3().setFromObject(laboratoryRoot);const sphere=laboratoryBounds.getBoundingSphere(new THREE.Sphere()),center=sphere.center.clone(),size=laboratoryBounds.getSize(new THREE.Vector3());center.y=THREE.MathUtils.clamp(center.y,2.2,Math.max(3.5,size.y*.56));runtime.orbit.target.copy(center);runtime.orbit.yaw=0;runtime.orbit.pitch=.10;runtime.orbit.distance=THREE.MathUtils.clamp(Math.max(12,Math.max(size.x,size.z)*.68),12,62);runtime.updateOrbit?.();document.body.dataset.laboratoryStartingView='ios-resilient-bounds-v63'}
  async function openLaboratory(){refreshRuntime();if(!runtime||mode()!=='interior')return false;if(entryPromise)return entryPromise;window.__castleBureauVideoPrime?.();showTransitionLoader('LABORATORY LOADING');document.body.dataset.laboratoryReady='loading';document.body.dataset.iosLaboratoryStage='opening-v63';entryPromise=(async()=>{try{const root=await ensureLaboratoryRoot();if(mode()!=='interior'){root.visible=false;return false}if(runtime.castleRoot)runtime.castleRoot.visible=false;if(runtime.interiorRoot)runtime.interiorRoot.visible=false;const cardGroup=findCardGroup();if(cardGroup)cardGroup.visible=false;root.visible=true;publishSceneState('laboratory');setLaboratoryStartingView();document.body.dataset.laboratoryReady='true';document.body.dataset.iosLaboratoryStage='visible-v63';window.__castleBureauVideoPlay?.();requestAnimationFrame(()=>requestAnimationFrame(()=>hideTransitionLoader()));return true}catch(error){document.body.dataset.laboratoryReady='false';document.body.dataset.iosLaboratoryStage='retry-available-v63';document.body.dataset.iosLaboratoryError=String(error?.message||error);hideTransitionLoader();return false}finally{entryPromise=null}})();return entryPromise}
  function restoreInterior(){refreshRuntime();if(!runtime?.interiorRoot)return false;showTransitionLoader('INTERIOR LOADING');if(laboratoryRoot)laboratoryRoot.visible=false;if(runtime.castleRoot)runtime.castleRoot.visible=false;runtime.interiorRoot.visible=true;const cardGroup=findCardGroup();if(cardGroup)cardGroup.visible=false;publishSceneState('interior');runtime.setInteriorStartingView?.();document.body.dataset.iosLaboratoryStage=laboratoryRoot?'cached-v63':'idle-v63';requestAnimationFrame(()=>requestAnimationFrame(()=>hideTransitionLoader()));return true}
  function scheduleWarmup(){if(warmTimer||laboratoryRoot||laboratoryBytes||laboratoryBytesPromise||mode()!=='interior')return;warmTimer=setTimeout(()=>{warmTimer=0;if(mode()!=='interior'||laboratoryRoot)return;fetchLaboratoryBytes({silent:true}).catch(()=>{})},450)}
  function interceptClick(event){const target=event.target?.closest?.('#bureau-of-ai, #laboratory-medallion-button, #return-exterior');if(!target)return;if(mode()==='laboratory'&&(target.id==='bureau-of-ai'||target.id==='return-exterior')){event.preventDefault();event.stopImmediatePropagation();restoreInterior();return}if(mode()==='interior'&&(target.id==='bureau-of-ai'||target.id==='laboratory-medallion-button')){event.preventDefault();event.stopImmediatePropagation();void openLaboratory()}}
  function interceptEscape(event){if(event.key!=='Escape'||mode()!=='laboratory')return;event.preventDefault();event.stopImmediatePropagation();restoreInterior()}
  function handleOpenEvent(event){if(mode()!=='interior')return;event?.preventDefault?.();void openLaboratory()}
  window.__castleOpenLaboratory=openLaboratory;window.__castleRestoreInteriorFromLaboratory=restoreInterior;window.__castleShowSceneLoader=showTransitionLoader;window.__castleHideSceneLoader=hideTransitionLoader;
  document.addEventListener('click',interceptClick,true);window.addEventListener('keydown',interceptEscape,true);window.addEventListener('castle-open-laboratory',handleOpenEvent,true);window.addEventListener('castleRuntimeReady',()=>{refreshRuntime();scheduleWarmup()});const observer=new MutationObserver(()=>{refreshRuntime();if(mode()==='interior')scheduleWarmup()});observer.observe(document.body,{attributes:true,attributeFilter:['data-scene-mode']});scheduleWarmup();
  window.addEventListener('pagehide',()=>{if(warmTimer)clearTimeout(warmTimer);activeFetchController?.abort?.('pagehide');observer.disconnect();document.removeEventListener('click',interceptClick,true);window.removeEventListener('keydown',interceptEscape,true);window.removeEventListener('castle-open-laboratory',handleOpenEvent,true);delete window.__castleOpenLaboratory;delete window.__castleRestoreInteriorFromLaboratory;delete window.__castleShowSceneLoader;delete window.__castleHideSceneLoader},{once:true});
}
