import * as THREE from 'three';
if(!window.__castleBureauVideoBridgeInstalled){
  window.__castleBureauVideoBridgeInstalled=true;
  const VIDEO_URL=new URL('../assets/assets/videos/bureau_screen_loop.mp4',document.baseURI).href,MAX_VIDEO_SURFACES=3,PRIME_WINDOW_MS=30000;
  let video=null,texture=null,material=null,boundRoot=null,boundMeshes=new Set(),observer=null,entryPrimed=false,entryPrimedAt=0;
  document.body.dataset.bureauVideoOwner='castle-bureau-video-bridge-v61';document.body.dataset.bureauVideoLegacyOwner='disabled-v61';
  const mode=()=>document.body.dataset.sceneMode||'exterior',isLaboratoryActive=()=>mode()==='laboratory'||mode()==='bureau';
  function findBureauRoot(){const r=window.__castleSearchRuntime;return r?.scene?.getObjectByName('BureauOfAI')||r?.bureauRoot||null}
  function scoreVideoMesh(o){if(!o?.isMesh)return 0;const mats=(Array.isArray(o.material)?o.material:[o.material]).map(m=>m?.name||'').join(' '),label=`${o.name||''} ${mats}`.toLowerCase();if(/videoscreen|video[_ -]?screen|videomesh|video mesh/.test(label))return 140;if(/video/.test(label))return 130;if(/screen/.test(label))return 120;if(/display|monitor/.test(label))return 110;if(/scry|mirror|portal|oval|central/.test(label))return 100;if(/circle|circular/.test(label))return 90;return 0}
  function discoverVideoMeshes(root){const scored=[];root.updateMatrixWorld(true);root.traverse(o=>{const s=scoreVideoMesh(o);if(s>0)scored.push({object:o,score:s})});scored.sort((a,b)=>b.score-a.score);const targets=[];for(const i of scored){if(targets.length>=MAX_VIDEO_SURFACES)break;if(!targets.includes(i.object))targets.push(i.object)}if(targets.length<MAX_VIDEO_SURFACES){const rb=new THREE.Box3().setFromObject(root),rc=rb.getCenter(new THREE.Vector3()),geo=[];root.traverse(o=>{if(!o?.isMesh||targets.includes(o))return;const b=new THREE.Box3().setFromObject(o);if(b.isEmpty())return;const s=b.getSize(new THREE.Vector3()),c=b.getCenter(new THREE.Vector3()),d=[Math.abs(s.x),Math.abs(s.y),Math.abs(s.z)].sort((a,b)=>a-b);if(d[0]>=.45||d[1]<=.35||d[2]>=8)return;geo.push({object:o,score:Math.hypot(c.x-rc.x,c.z-rc.z)+Math.abs(c.y-rc.y)*.35})});geo.sort((a,b)=>a.score-b.score);for(const i of geo){if(targets.length>=MAX_VIDEO_SURFACES)break;if(!targets.includes(i.object))targets.push(i.object)}}return targets}
  function ensureVideoTexture(){if(texture)return texture;video=document.createElement('video');video.id='bureau-screen-loop-video';Object.assign(video,{src:VIDEO_URL,loop:true,muted:true,defaultMuted:true,playsInline:true,preload:'auto',crossOrigin:'anonymous',autoplay:false});video.setAttribute('playsinline','');video.setAttribute('webkit-playsinline','');video.setAttribute('muted','');video.setAttribute('aria-hidden','true');Object.assign(video.style,{position:'fixed',width:'1px',height:'1px',left:'-4px',top:'-4px',opacity:'0',pointerEvents:'none'});document.body.appendChild(video);video.load();texture=new THREE.VideoTexture(video);texture.colorSpace=THREE.SRGBColorSpace;texture.minFilter=THREE.LinearFilter;texture.magFilter=THREE.LinearFilter;texture.generateMipmaps=false;texture.flipY=false;material=new THREE.MeshBasicMaterial({name:'bureau-live-video-material-v61',map:texture,color:0xffffff,side:THREE.DoubleSide,toneMapped:false});return texture}
  function bindScreens(root){if(!root)return false;ensureVideoTexture();if(boundRoot!==root){boundRoot=root;boundMeshes=new Set()}const targets=discoverVideoMeshes(root);for(const o of targets){if(!o.userData.__laboratoryVideoFacingFixed){o.rotation.y+=Math.PI;o.userData.__laboratoryVideoFacingFixed=true}o.material=material;o.material.needsUpdate=true;o.visible=true;boundMeshes.add(o)}document.body.dataset.bureauVideoAsset=VIDEO_URL;document.body.dataset.bureauVideoScreenCount=String(targets.length);document.body.dataset.bureauVideoState=targets.length?'single-owner-ready-v61':'screen-mismatch-v61';return targets.length>0}
  function configurePlayback(){if(!video)return;video.muted=true;video.defaultMuted=true;video.loop=true;video.playsInline=true;video.setAttribute('playsinline','');video.setAttribute('webkit-playsinline','')}
  function attemptPlay(reason){ensureVideoTexture();configurePlayback();if(!video.paused&&!video.ended){document.body.dataset.bureauVideoPlayback='playing-loop-v61';delete document.body.dataset.bureauVideoError;return Promise.resolve(true)}document.body.dataset.bureauVideoPlayback=`${reason}-attempt-v61`;return video.play().then(()=>{document.body.dataset.bureauVideoPlayback='playing-loop-v61';delete document.body.dataset.bureauVideoError;return true}).catch(e=>{document.body.dataset.bureauVideoPlayback='waiting-user-gesture-v61';document.body.dataset.bureauVideoError=String(e?.message||e);return false})}
  function primeFromGesture(){entryPrimed=true;entryPrimedAt=performance.now();ensureVideoTexture();if(video.ended){try{video.currentTime=0}catch(_){}}document.body.dataset.bureauVideoGesturePrime='armed-v61';return attemptPlay('gesture-prime')}
  function keepPrimedDuringEntry(){return entryPrimed&&mode()==='interior'&&performance.now()-entryPrimedAt<PRIME_WINDOW_MS}
  function syncPlayback(){if(isLaboratoryActive()){entryPrimed=false;const root=findBureauRoot();if(root)bindScreens(root);if(!video)ensureVideoTexture();if(video.paused)attemptPlay('laboratory-entry');else document.body.dataset.bureauVideoPlayback='playing-loop-v61';return}if(keepPrimedDuringEntry()){document.body.dataset.bureauVideoPlayback=video?.paused?'gesture-primed-pending-v61':'gesture-primed-playing-v61';return}entryPrimed=false;if(video&&!video.paused)video.pause();document.body.dataset.bureauVideoPlayback='paused-v61'}
  function hydrate(){const root=findBureauRoot();if(root)bindScreens(root);syncPlayback()}
  function isBureauEntryTarget(event){if(mode()!=='interior')return false;const t=event?.target;return Boolean(t?.closest?.('#bureau-of-ai, #laboratory-medallion-button'))}
  function gestureResume(event){if(isBureauEntryTarget(event)){document.body.dataset.bureauVideoGestureSource=event?.target?.closest?.('#laboratory-medallion-button')?'laboratory-medallion-v61':'bureau-control-v61';primeFromGesture();return}if(isLaboratoryActive())attemptPlay('gesture-resume')}
  window.__castleBureauVideoPrime=primeFromGesture;window.__castleBureauVideoPlay=hydrate;window.addEventListener('castleRuntimeReady',hydrate);window.addEventListener('pointerdown',gestureResume,{capture:true,passive:true});window.addEventListener('touchstart',gestureResume,{capture:true,passive:true});window.addEventListener('click',gestureResume,{capture:true,passive:true});
  observer=new MutationObserver(()=>{hydrate();if(isLaboratoryActive()){requestAnimationFrame(hydrate);setTimeout(hydrate,120);setTimeout(hydrate,420);setTimeout(hydrate,900)}});observer.observe(document.body,{attributes:true,attributeFilter:['data-scene-mode','data-laboratory-ready','data-bureau-ready']});let attempts=0;const timer=setInterval(()=>{hydrate();if((boundRoot&&boundMeshes.size>0&&video?.readyState>=2)||attempts++>300)clearInterval(timer)},200);
  window.addEventListener('beforeunload',()=>{clearInterval(timer);observer?.disconnect();video?.pause();material?.dispose();texture?.dispose();video?.remove();delete window.__castleBureauVideoPrime;delete window.__castleBureauVideoPlay},{once:true});hydrate();
}
