import * as THREE from 'three';
import { CastleJesterGatekeeper } from './castle_jester_gatekeeper.js?v=61';

const modelUrl=new URL('../assets/assets/models/castle_jester_rigged.glb',document.baseURI).href;
const MOVE_SLOP_PX=6;
const JESTER_MODEL_FORWARD_OFFSET=Math.PI*.5;
const GATE_STANDOFF=1.05;
document.body.dataset.castleJesterAsset=modelUrl;
document.body.dataset.castleEntranceTrigger='jester-exact-hit-pointerup-v84';
document.body.dataset.castleJesterIntegration='waiting-for-runtime';
document.body.dataset.castleJesterRotationOwner='castle-front-gate-v72';
let gatekeeper=null,frame=0,previousTime=performance.now(),pointerDown=null,activeRuntime=null;
const isExterior=()=>document.body.dataset.sceneMode==='exterior';
function rotateExistingCardAnchorsWithCastle(scene,castleRoot,angle){if(!scene||!castleRoot)return;scene.updateMatrixWorld(true);const axis=new THREE.Vector3(0,1,0),turn=new THREE.Quaternion().setFromAxisAngle(axis,angle),pivot=castleRoot.getWorldPosition(new THREE.Vector3());for(const group of scene.children){if(!group?.isGroup||group===castleRoot)continue;for(const mesh of group.children?.filter(item=>item?.userData?.card)||[]){const parent=mesh.parent;if(!parent)continue;const p=mesh.getWorldPosition(new THREE.Vector3()).sub(pivot).applyQuaternion(turn).add(pivot);const q=mesh.getWorldQuaternion(new THREE.Quaternion()).premultiply(turn);mesh.position.copy(parent.worldToLocal(p));mesh.quaternion.copy(parent.getWorldQuaternion(new THREE.Quaternion()).invert().multiply(q));mesh.updateMatrixWorld(true)}}}
function alignCastleToPlaza(castleRoot){if(!castleRoot||castleRoot.userData.unoPlazaAligned)return;const angle=Math.PI*1.5;castleRoot.rotation.y+=angle;castleRoot.updateMatrixWorld(true);rotateExistingCardAnchorsWithCastle(castleRoot.parent,castleRoot,angle);castleRoot.userData.unoPlazaAligned=true;}
function findPortalAnchor(castleRoot){if(!castleRoot)return null;castleRoot.updateMatrixWorld(true);const pattern=/(main\s*)?(gate|gateway|portal|entrance|entry|door)/i;let best=null,score=-Infinity;castleRoot.traverse(o=>{const label=[o.name,o.userData?.name,o.userData?.label].filter(Boolean).join(' ');if(!pattern.test(label))return;const p=o.getWorldPosition(new THREE.Vector3());const s=(/gate|gateway|portal/i.test(label)?40:20)+(/main|front|entrance/i.test(label)?20:0)-Math.abs(p.y)*.15;if(s>score){score=s;best={object:o,position:p,label}}});return best;}
function orientBodyOutward(outward){if(gatekeeper?.root&&outward)gatekeeper.root.rotation.y=Math.atan2(outward.x,outward.z)+JESTER_MODEL_FORWARD_OFFSET;}
function placeAtGate(castleRoot){if(!gatekeeper||!castleRoot||gatekeeper.clicked||!isExterior())return;alignCastleToPlaza(castleRoot);const box=new THREE.Box3().setFromObject(castleRoot);if(box.isEmpty())return;const size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),anchor=findPortalAnchor(castleRoot),outward=new THREE.Vector3(0,0,1);if(anchor){outward.copy(anchor.position).sub(center);outward.y=0;if(outward.lengthSq()<1e-5)outward.set(0,0,1);else outward.normalize();gatekeeper.root.position.copy(anchor.position).addScaledVector(outward,GATE_STANDOFF);gatekeeper.root.position.y=box.min.y+.04;}else gatekeeper.root.position.set(center.x,box.min.y+.04,box.max.z+Math.max(1.05,size.z*.038));orientBodyOutward(outward);}
function stop(e){e.preventDefault();e.stopImmediatePropagation();}
function requestEntrance(){if(!isExterior())return;document.body.dataset.castleJesterState='opening-gate';gatekeeper?.setVisible(false);window.dispatchEvent(new CustomEvent('castleJesterEnter'));}
function exactHit(event){return gatekeeper?.hitTest(event)===true;}
function installPointerHandlers(canvas){if(canvas.dataset.castleJesterPointerHandlersV84==='true')return;canvas.dataset.castleJesterPointerHandlersV84='true';
 canvas.addEventListener('pointerdown',event=>{if(!isExterior())return;const hit=exactHit(event);pointerDown={pointerId:event.pointerId,x:event.clientX,y:event.clientY,jester:hit,moved:false};if(hit)canvas.style.cursor='pointer';},true);
 canvas.addEventListener('pointermove',event=>{if(!isExterior())return;if(pointerDown?.pointerId===event.pointerId&&Math.hypot(event.clientX-pointerDown.x,event.clientY-pointerDown.y)>MOVE_SLOP_PX)pointerDown.moved=true;canvas.style.cursor=exactHit(event)?'pointer':'';},true);
 canvas.addEventListener('pointerup',event=>{if(!isExterior()){pointerDown=null;return;}const down=pointerDown;pointerDown=null;if(!down||down.pointerId!==event.pointerId||down.moved||!down.jester||!exactHit(event))return;if(!gatekeeper.click(event,true))return;gatekeeper.enterDispatched=true;gatekeeper.clearHover();canvas.style.cursor='';document.body.dataset.castleJesterGesture='exact-jester-pointerup-v84';requestEntrance();stop(event);},true);
 canvas.addEventListener('pointercancel',()=>{pointerDown=null;gatekeeper?.clearHover();canvas.style.cursor='';},true);
 canvas.addEventListener('pointerleave',()=>{pointerDown=null;gatekeeper?.clearHover();canvas.style.cursor='';},true);
}
function animate(now){const delta=Math.min(.05,Math.max(0,(now-previousTime)/1000));previousTime=now;if(gatekeeper){const exterior=isExterior();gatekeeper.setVisible(exterior);if(exterior&&!gatekeeper.clicked)placeAtGate(activeRuntime?.castleRoot);if(exterior)gatekeeper.update(delta);}frame=requestAnimationFrame(animate);}
function install(runtime){if(!runtime?.scene||!runtime?.camera||!runtime?.renderer)return;if(activeRuntime===runtime&&gatekeeper){installPointerHandlers(runtime.renderer.domElement);return;}activeRuntime=runtime;alignCastleToPlaza(runtime.castleRoot);gatekeeper?.dispose();gatekeeper=new CastleJesterGatekeeper({scene:runtime.scene,camera:runtime.camera,renderer:runtime.renderer,onEnterRequested:requestEntrance,modelUrl});gatekeeper.setVisible(isExterior());installPointerHandlers(runtime.renderer.domElement);document.body.dataset.castleJesterIntegration='active-exact-hit-v84';if(!frame){previousTime=performance.now();frame=requestAnimationFrame(animate);}}
function tryInstall(){const r=window.__castleSearchRuntime;if(r){install(r);return true;}return false;}
window.addEventListener('castleRuntimeReady',tryInstall,{passive:true});if(!tryInstall()){let n=0;const timer=setInterval(()=>{if(tryInstall()||n++>160)clearInterval(timer)},100);}
let previousSceneMode=document.body.dataset.sceneMode||'exterior';const observer=new MutationObserver(()=>{const m=document.body.dataset.sceneMode||'exterior';if(m===previousSceneMode)return;const from=previousSceneMode;previousSceneMode=m;pointerDown=null;if(m!=='exterior'){gatekeeper?.setVisible(false);gatekeeper?.clearHover();return;}if(from!=='exterior'&&gatekeeper){gatekeeper.restartLoop?.();placeAtGate(activeRuntime?.castleRoot);gatekeeper.setVisible(true);}});observer.observe(document.body,{attributes:true,attributeFilter:['data-scene-mode']});
window.addEventListener('beforeunload',()=>{observer.disconnect();if(frame)cancelAnimationFrame(frame);gatekeeper?.dispose();},{once:true});
