const LOADER_ART_URL=new URL('../assets/assets/images/castle_jester_loading_bar.png',document.baseURI).href;
if(!window.__castleSharedTransitionLoaderV65Installed){
 window.__castleSharedTransitionLoaderV65Installed=true;let timer=0,value=0;
 function ensure(){let root=document.getElementById('castle-shared-transition-loader');if(root)return root;const style=document.createElement('style');style.textContent=`#castle-shared-transition-loader{position:fixed;inset:0;z-index:2147483647;display:grid;place-items:center;background:radial-gradient(circle at 50% 44%,rgba(66,6,5,.42),rgba(2,6,11,.96) 58%,#02060b);opacity:0;visibility:hidden;pointer-events:none;transition:opacity .22s ease,visibility .22s ease}#castle-shared-transition-loader.is-visible{opacity:1;visibility:visible;pointer-events:auto}.scene-loader-shell{width:min(96vw,1280px);text-align:center;padding:18px}.scene-loader-art{position:relative;width:100%;aspect-ratio:3/1;margin:auto;filter:drop-shadow(0 18px 30px rgba(0,0,0,.7))}.scene-loader-base{position:absolute;inset:0;background:url('${LOADER_ART_URL}') center/contain no-repeat;filter:brightness(.5) saturate(.68)}.scene-loader-track{position:absolute;left:5.4%;right:5.4%;top:45%;height:11%;border-radius:999px;overflow:hidden;z-index:2;box-shadow:inset 0 0 12px rgba(0,0,0,.92)}.scene-loader-fill{position:absolute;inset:0 auto 0 0;width:0;border-radius:999px;background:repeating-linear-gradient(90deg,#66100d 0 18px,#9d1a11 18px 36px,#d43217 36px 54px,#ff7d2d 54px 72px);box-shadow:inset 0 0 18px rgba(255,175,70,.75),0 0 18px rgba(255,64,18,.62);transition:width .22s ease}.scene-loader-percent{margin-top:8px;color:#e8b660;font:600 clamp(26px,4vw,44px)/1.1 Georgia,serif;text-shadow:0 2px 12px rgba(0,0,0,.8)}.scene-loader-stage{margin-top:8px;color:#d7c8b0;font:600 clamp(13px,2vw,18px)/1.2 Georgia,serif;letter-spacing:.18em;text-transform:uppercase}@media(max-width:700px){.scene-loader-shell{width:96vw;padding:8px}.scene-loader-track{left:5.8%;right:5.8%;top:45%;height:11%}.scene-loader-percent{margin-top:2px;font-size:clamp(24px,8vw,34px)}.scene-loader-stage{font-size:clamp(12px,3.6vw,16px);letter-spacing:.12em}}`;document.head.append(style);root=document.createElement('div');root.id='castle-shared-transition-loader';root.innerHTML='<div class="scene-loader-shell"><div class="scene-loader-art"><div class="scene-loader-base"></div><div class="scene-loader-track"><div class="scene-loader-fill"></div></div></div><div class="scene-loader-percent">0%</div><div class="scene-loader-stage">INITIALISATION</div></div>';document.body.append(root);return root;}
 function progress(v){const root=ensure();value=Math.max(0,Math.min(100,v));root.querySelector('.scene-loader-fill').style.width=value+'%';root.querySelector('.scene-loader-percent').textContent=Math.round(value)+'%';}
 function show(label){const root=ensure();clearInterval(timer);value=0;progress(3);root.querySelector('.scene-loader-stage').textContent=label||'LOADING';root.classList.add('is-visible');timer=setInterval(()=>{if(value<90)progress(value+Math.max(.8,(92-value)*.07));},180);document.body.dataset.castleSharedLoader='visible-v65';}
 function hide(){const root=document.getElementById('castle-shared-transition-loader');if(!root)return;clearInterval(timer);progress(100);root.querySelector('.scene-loader-stage').textContent='READY';setTimeout(()=>{root.classList.remove('is-visible');document.body.dataset.castleSharedLoader='hidden-v65';},280);}
 window.__castleShowSceneLoader=show;window.__castleSetSceneLoaderProgress=progress;window.__castleHideSceneLoader=hide;
 window.addEventListener('castleJesterEnter',()=>show('INTERIOR LOADING'),true);
}
