import 'package:flutter_test/flutter_test.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:uno_chanson_2/core/app_router.dart';
import 'package:uno_chanson_2/models/card_image_model.dart';
import 'package:uno_chanson_2/models/deck_model.dart';
import 'package:uno_chanson_2/services/external_ai_handoff_service.dart';

void main() {
  final applicationUri = Uri(
    scheme: 'https',
    host: 'www.chanson-a-repondre-uno.scot',
    path: '/',
  );

  test('transcription handoff gives external AI canonical card and image URLs', () {
    final prompt = ExternalAiHandoffService.buildPrompt(
      mode: CardAiHandoffMode.transcribe,
      card: _card(),
      deck: _deck(),
      applicationUri: applicationUri,
    );

    expect(
      prompt,
      contains('https://www.chanson-a-repondre-uno.scot/share/BRIO-013/'),
    );
    expect(
      prompt,
      contains(
        'https://www.chanson-a-repondre-uno.scot/assets/assets/decks/'
        'chanson_a_repondre_brio/cards/013.jpeg',
      ),
    );
    expect(prompt, contains('Open and analyze the CARD IMAGE directly.'));
    expect(prompt, contains('Transcribe every readable word from the image.'));
    expect(prompt, contains('Do not depend on an app backend'));
    expect(prompt, isNot(contains('run TRANSCRIBE CARD')));
  });

  test('DIY handoff analyzes image directly without requiring transcription', () {
    final prompt = ExternalAiHandoffService.buildPrompt(
      mode: CardAiHandoffMode.diy,
      card: _card(),
      deck: _deck(),
      applicationUri: applicationUri,
    );

    expect(prompt, contains('CARD IMAGE:'));
    expect(prompt, contains('Treat the image itself as the primary source.'));
    expect(prompt, contains('Discuss this card with me based on what you can read and see in the image.'));
    expect(prompt, contains('Do not depend on an app backend'));
    expect(prompt, isNot(contains('[not available]')));
    expect(prompt, isNot(contains('requires a transcription generated by the app')));
  });

  test('existing transcription is optional comparison text, not a requirement', () {
    final prompt = ExternalAiHandoffService.buildPrompt(
      mode: CardAiHandoffMode.diy,
      card: _card(transcription: 'old text'),
      deck: _deck(),
      transcriptionOverride: 'fresh comparison text',
      applicationUri: applicationUri,
    );

    expect(prompt, contains('OPTIONAL EXISTING TEXT FOR COMPARISON:'));
    expect(prompt, contains('fresh comparison text'));
    expect(prompt, isNot(contains('old text')));
    expect(prompt, contains('Verify it against the image before relying on it.'));
  });

  test('public image URL preserves GitHub Pages project base path', () {
    final image = ExternalAiHandoffService.publicImageUrlFor(
      card: _card(),
      applicationUri: Uri.parse(
        'https://dupuis-scot.github.io/CHANSON-A-REPONDRE-UNO/#/cards',
      ),
    );

    expect(
      image.toString(),
      'https://dupuis-scot.github.io/CHANSON-A-REPONDRE-UNO/assets/assets/'
      'decks/chanson_a_repondre_brio/cards/013.jpeg',
    );
  });

  test('transcription navigation opens the dedicated transcription route', () {
    expect(
      AppRoutes.transcription('brio-013'),
      '/cards/brio-013/transcription',
    );
    expect(
      AppRoutes.transcription('final-84-01'),
      '/cards/final-84-01/transcription',
    );
  });

  test('provider handoff copies the prompt and opens the provider', () async {
    String? copied;
    Uri? launched;
    LaunchMode? launchMode;
    final service = ExternalAiHandoffService(
      promptCopier: (value) async => copied = value,
      launcher: (uri, {required mode}) async {
        launched = uri;
        launchMode = mode;
        return true;
      },
    );

    await service.openProvider(
      provider: ExternalAiProvider.chatgpt,
      prompt: 'prepared prompt',
    );

    expect(copied, 'prepared prompt');
    expect(launched, Uri.parse('https://chatgpt.com/'));
    expect(launchMode, LaunchMode.externalApplication);
  });

  test('all supported DIY providers have external entry URLs', () {
    expect(ExternalAiProvider.chatgpt.uri.host, 'chatgpt.com');
    expect(ExternalAiProvider.gemini.uri.host, 'gemini.google.com');
    expect(ExternalAiProvider.claude.uri.host, 'claude.ai');
    expect(ExternalAiProvider.copilot.uri.host, 'copilot.microsoft.com');
  });
}

CardImageModel _card({String? transcription}) => CardImageModel(
  id: 'brio-013',
  deckId: 'chanson-a-repondre-brio',
  title: 'Le Kraken',
  path: 'assets/decks/chanson_a_repondre_brio/cards/013.jpeg',
  category: 'CYBERPUNK',
  colour: 'green',
  importedAt: DateTime.fromMillisecondsSinceEpoch(0),
  transcription: transcription,
);

Deck _deck() => Deck(
  id: 'chanson-a-repondre-brio',
  name: 'Chanson à répondre BRIO',
  cards: [_card()],
);
