import 'package:flutter/services.dart';
import 'package:url_launcher/url_launcher.dart';

import '../models/card_image_model.dart';
import '../models/deck_model.dart';
import 'public_card_share_service.dart';

typedef ExternalAiUrlLauncher =
    Future<bool> Function(Uri uri, {required LaunchMode mode});
typedef ExternalAiPromptCopier = Future<void> Function(String value);

enum CardAiHandoffMode { transcribe, diy }

enum ExternalAiProvider { chatgpt, gemini, claude, copilot }

extension ExternalAiProviderDetails on ExternalAiProvider {
  String get label => switch (this) {
    ExternalAiProvider.chatgpt => 'ChatGPT',
    ExternalAiProvider.gemini => 'Gemini',
    ExternalAiProvider.claude => 'Claude',
    ExternalAiProvider.copilot => 'Copilot',
  };

  Uri get uri => switch (this) {
    ExternalAiProvider.chatgpt => Uri.parse('https://chatgpt.com/'),
    ExternalAiProvider.gemini => Uri.parse('https://gemini.google.com/app'),
    ExternalAiProvider.claude => Uri.parse('https://claude.ai/new'),
    ExternalAiProvider.copilot => Uri.parse('https://copilot.microsoft.com/'),
  };
}

class ExternalAiHandoffService {
  const ExternalAiHandoffService({
    ExternalAiUrlLauncher? launcher,
    ExternalAiPromptCopier? promptCopier,
  }) : _launcher = launcher ?? launchUrl,
       _promptCopier = promptCopier ?? _copyPrompt;

  final ExternalAiUrlLauncher _launcher;
  final ExternalAiPromptCopier _promptCopier;

  static String transcriptionFor(
    CardImageModel card, {
    String? transcriptionOverride,
  }) {
    for (final value in <String?>[
      transcriptionOverride,
      card.cleanedTranscription,
      card.transcription,
    ]) {
      final text = value?.trim() ?? '';
      if (text.isNotEmpty) return text;
    }
    return '';
  }

  static String buildPrompt({
    required CardAiHandoffMode mode,
    required CardImageModel card,
    required Deck deck,
    String? transcriptionOverride,
    Uri? applicationUri,
  }) {
    final shareUrl = PublicCardShareService.shareUrlFor(
      cardId: card.id,
      deckId: deck.id,
      applicationUri: applicationUri,
    );
    final transcription = transcriptionFor(
      card,
      transcriptionOverride: transcriptionOverride,
    );
    final heading = <String>[
      '${deck.name} — ${card.displayTitle}',
      'Card ID: ${card.id}',
      'SOURCE CARD:',
      '$shareUrl',
      '',
    ];

    if (mode == CardAiHandoffMode.transcribe) {
      if (transcription.isNotEmpty) {
        return <String>[
          ...heading,
          'CARD TRANSCRIPTION:',
          transcription,
          '',
          'Review this transcription against the source card if you can see the image.',
          'Preserve the original language, accents, punctuation, capitalization, headings, and meaningful line breaks.',
          'Do not summarize, rewrite, translate, or invent missing text. If a word cannot be read confidently, mark it as [unclear].',
        ].join('\n');
      }
      return <String>[
        ...heading,
        'No transcription was supplied by the app.',
        'Do not depend on scraping the source webpage for card text.',
        'Return to the app and run TRANSCRIBE CARD before handing this card to an external AI.',
      ].join('\n');
    }

    if (transcription.isEmpty) {
      return <String>[
        ...heading,
        'CARD TRANSCRIPTION:',
        '[not available]',
        '',
        'This handoff requires a transcription generated by the app.',
        'Do not ask me to paste or upload the card text and do not depend on scraping the source webpage.',
      ].join('\n');
    }

    return <String>[
      ...heading,
      'CARD TRANSCRIPTION:',
      transcription,
      '',
      'Discuss this card with me using the transcription above as the primary source.',
      'The source card link is optional visual/reference context only; do not depend on scraping it for the text.',
      'Do not ask me to paste or upload the card text again.',
      'You can help me discuss, interpret, translate, fact-check, research, critique, or brainstorm from this transcription.',
    ].join('\n');
  }

  Future<void> copyPrompt(String prompt) => _promptCopier(prompt);

  Future<void> openProvider({
    required ExternalAiProvider provider,
    required String prompt,
  }) async {
    // Start both operations inside the original tap/click event so Web browsers
    // do not treat the external tab as an unsolicited popup after an await.
    final copyFuture = _promptCopier(prompt);
    final launchFuture = _launcher(
      provider.uri,
      mode: LaunchMode.externalApplication,
    );
    final launched = await launchFuture;
    await copyFuture;
    if (!launched) {
      throw StateError('Could not open ${provider.label}.');
    }
  }

  static Future<void> _copyPrompt(String value) =>
      Clipboard.setData(ClipboardData(text: value));
}
