import * as THREE from 'three';
import { GLTFLoader } from '../vendor/GLTFLoader.js';
import { DRACOLoader } from 'https://threejs.org/examples/jsm/loaders/DRACOLoader.js';

const host = document.querySelector('#stage');
const bar = document.querySelector('#bar');
const status = document.querySelector('#status');
const progress = document.querySelector('#progress');
const scene = new THREE.Scene(); scene.background=null; scene.fog=null;
const camera=new THREE.PerspectiveCamera(54,innerWidth/innerHeight,.02,5000);let yaw=0,pitch=0,movementBounds=null,worldRadius=100;
const IS_IOS=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,premultipliedAlpha:true,powerPreference:'high-performance'});renderer.setClearColor(0x000000,0);renderer.setPixelRatio(Math.min(devicePixelRatio,IS_IOS?1.18:1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.45;host.appendChild(renderer.domElement);
const ambient=new THREE.AmbientLight(0xffd6bd,1.15),hemi=new THREE.HemisphereLight(0x8bd9ff,0x32100a,1.25),warmKey=new THREE.DirectionalLight(0xffa452,3.1),coldFill=new THREE.DirectionalLight(0x72dfff,1.75),coreGlow=new THREE.PointLight(0xff4e18,110,300,1.55),cyanA=new THREE.PointLight(0x2affdf,98,190,1.6),cyanB=new THREE.PointLight(0x66dcff,82,180,1.6);warmKey.position.set(-24,46,26);coldFill.position.set(32,28,-34);scene.add(ambient,hemi,warmKey,coldFill,coreGlow,cyanA,cyanB,warmKey.target,coldFill.target);
function setStatus(label,pct){status.textContent=label;status.style.opacity='1';progress.style.opacity='1';if(Number.isFinite(pct))bar.style.width=`${THREE.MathUtils.clamp(pct,0,100)}%`}
function finishLoad(meshes){setStatus(`MEGAPOLE OPEN · ${meshes} MESH${meshes===1?'':'ES'}`,100);setTimeout(()=>{status.style.opacity='0';progress.style.opacity='0'},1800)}
async function meshopt(){try{const mod=await import('../vendor/meshopt_decoder.module.js');await mod.MeshoptDecoder?.ready;return mod.MeshoptDecoder||null}catch(e){console.warn('MEGAPOLE Meshopt unavailable',e);return null}}
const draco=new DRACOLoader();draco.setDecoderPath('https://www.gstatic.com/draco/versioned/decoders/1.5.7/');draco.setWorkerLimit(IS_IOS?1:2);
function loadGlb(url,decoder){return new Promise((resolve,reject)=>{const loader=new GLTFLoader();loader.setDRACOLoader(draco);if(decoder)loader.setMeshoptDecoder(decoder);loader.load(url,resolve,xhr=>{if(xhr.total)setStatus("LOADING SILMARI'LLION MEGAPOLE",Math.min(99,xhr.loaded/xhr.total*100))},reject)})}
function tuneTexture(t,srgb=false){if(!t)return;if(srgb)t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());t.needsUpdate=true}
function preservePbrMaterial(m){if(!m)return;tuneTexture(m.map,true);tuneTexture(m.emissiveMap,true);tuneTexture(m.normalMap);tuneTexture(m.roughnessMap);tuneTexture(m.metalnessMap);tuneTexture(m.aoMap);m.side=THREE.DoubleSide;m.depthTest=true;m.visible=true;if(m.transparent||m.opacity<1)m.depthWrite=false;if(m.isMeshStandardMaterial||m.isMeshPhysicalMaterial){m.roughness=THREE.MathUtils.clamp(m.roughness??.72,.08,.96);m.metalness=THREE.MathUtils.clamp(m.metalness??.12,0,.9);if(m.emissiveMap)m.emissiveIntensity=Math.max(m.emissiveIntensity||1,1.35)}m.needsUpdate=true}
function fitDistanceForSphere(r){const v=THREE.MathUtils.degToRad(camera.fov),h=2*Math.atan(Math.tan(v/2)*camera.aspect);return r/Math.sin(Math.max(.2,Math.min(v,h))/2)}
function frame(root){root.visible=true;root.updateMatrixWorld(true);let box=new THREE.Box3().setFromObject(root);if(box.isEmpty())return 0;let size=box.getSize(new THREE.Vector3()),maxDim=Math.max(size.x,size.y,size.z);if(!Number.isFinite(maxDim)||maxDim<=0)return 0;if(maxDim<60||maxDim>420){root.scale.multiplyScalar(220/maxDim);root.updateMatrixWorld(true);box=new THREE.Box3().setFromObject(root);size=box.getSize(new THREE.Vector3())}const center=box.getCenter(new THREE.Vector3());root.position.sub(center);root.updateMatrixWorld(true);box=new THREE.Box3().setFromObject(root);size=box.getSize(new THREE.Vector3());let meshes=0;root.traverse(o=>{if(!o.isMesh)return;meshes++;o.visible=true;o.frustumCulled=false;o.renderOrder=1;(Array.isArray(o.material)?o.material:[o.material]).forEach(preservePbrMaterial)});if(!meshes)return 0;const sphere=box.getBoundingSphere(new THREE.Sphere());worldRadius=Math.max(sphere.radius,1);const distance=fitDistanceForSphere(worldRadius)*1.08,eye=THREE.MathUtils.clamp(size.y*.10,4,18);camera.position.set(0,eye,distance);camera.near=Math.max(.02,worldRadius/5000);camera.far=Math.max(1500,worldRadius*30,distance+worldRadius*12);camera.updateProjectionMatrix();camera.lookAt(0,0,0);camera.rotation.order='YXZ';yaw=camera.rotation.y;pitch=camera.rotation.x;movementBounds=new THREE.Box3(new THREE.Vector3(-size.x,-Math.max(size.y,.1),-size.z),new THREE.Vector3(size.x,Math.max(size.y*1.2,20),Math.max(distance,size.z*1.4)));scene.fog=new THREE.Fog(0x16090a,Math.max(worldRadius*2.2,distance*.65),Math.max(worldRadius*7,distance+worldRadius*4));coreGlow.position.set(0,Math.max(8,size.y*.18),size.z*.12);cyanA.position.set(-size.x*.18,Math.max(3,size.y*.07),size.z*.06);cyanB.position.set(size.x*.14,Math.max(3,size.y*.08),-size.z*.01);warmKey.target.position.set(0,size.y*.16,0);coldFill.target.position.set(0,size.y*.32,-size.z*.12);console.info('MEGAPOLE V14 Draco framed',{meshes,size:size.toArray(),radius:worldRadius,distance});return meshes}
async function install(){setStatus('INITIALIZING DRACO · MEGAPOLE',3);const decoder=await meshopt();try{const url='/assets/assets/models/SILMARI_LLION_MEGAPOLE_LUBIAK.glb?v=20260830-megapole-v14-draco';const gltf=await loadGlb(url,decoder);if(!gltf?.scene)throw new Error('GLB scene missing');gltf.scene.name='SILMARI_LLION_MEGAPOLE_PBR';scene.add(gltf.scene);const meshes=frame(gltf.scene);if(!meshes)throw new Error('Megapole contains no renderable mesh');renderer.render(scene,camera);finishLoad(meshes)}catch(error){console.error('Megapole GLB failed',error);setStatus(`MEGAPOLE GLB ERROR · ${error?.message||'RELOAD'}`,100)}}
const keys=new Set();addEventListener('keydown',e=>keys.add(e.key.toLowerCase()));addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));let drag=null;renderer.domElement.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,id:e.pointerId};renderer.domElement.setPointerCapture(e.pointerId);e.preventDefault()});renderer.domElement.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;yaw-=(e.clientX-drag.x)*.0042;pitch-=(e.clientY-drag.y)*.0032;pitch=THREE.MathUtils.clamp(pitch,-1.18,1.05);drag.x=e.clientX;drag.y=e.clientY});function releasePointer(e){if(!drag||e.pointerId!==drag.id)return;try{renderer.domElement.releasePointerCapture(e.pointerId)}catch{}drag=null}renderer.domElement.addEventListener('pointerup',releasePointer);renderer.domElement.addEventListener('pointercancel',releasePointer);renderer.domElement.addEventListener('wheel',e=>{const cp=Math.cos(pitch),f=new THREE.Vector3(Math.sin(yaw)*cp,Math.sin(-pitch),-Math.cos(yaw)*cp).normalize();camera.position.addScaledVector(f,-Math.sign(e.deltaY)*Math.max(1.8,worldRadius*.018));if(movementBounds)camera.position.clamp(movementBounds.min,movementBounds.max)},{passive:true});
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04),t=performance.now()*.001,speed=Math.max(8,worldRadius*.055)*dt,cp=Math.cos(pitch),f3=new THREE.Vector3(Math.sin(yaw)*cp,Math.sin(-pitch),-Math.cos(yaw)*cp).normalize(),f=new THREE.Vector3(f3.x,0,f3.z).normalize(),r=new THREE.Vector3(Math.cos(yaw),0,Math.sin(yaw));if(keys.has('w')||keys.has('arrowup'))camera.position.addScaledVector(f,speed);if(keys.has('s')||keys.has('arrowdown'))camera.position.addScaledVector(f,-speed);if(keys.has('a')||keys.has('arrowleft'))camera.position.addScaledVector(r,-speed);if(keys.has('d')||keys.has('arrowright'))camera.position.addScaledVector(r,speed);if(keys.has(' ')||keys.has('pageup')||keys.has('e'))camera.position.y+=speed;if(keys.has('control')||keys.has('pagedown')||keys.has('q'))camera.position.y-=speed;if(movementBounds)camera.position.clamp(movementBounds.min,movementBounds.max);coreGlow.intensity=105+Math.sin(t*.9)*8;cyanA.intensity=94+Math.sin(t*1.8)*13;cyanB.intensity=78+Math.sin(t*2.1+1.2)*11;camera.rotation.order='YXZ';camera.rotation.y=yaw;camera.rotation.x=pitch;renderer.render(scene,camera)}animate();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,IS_IOS?1.18:1.5));renderer.setSize(innerWidth,innerHeight)});install();