import * as THREE from 'three';
import { GLTFLoader } from '../vendor/GLTFLoader.js';
const host=document.querySelector('#stage'),bar=document.querySelector('#bar'),status=document.querySelector('#status'),progress=document.querySelector('#progress');
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x12090a); scene.fog=new THREE.FogExp2(0x160a0b,.00048);
const camera=new THREE.PerspectiveCamera(54,innerWidth/innerHeight,.03,5000); let yaw=0,pitch=-.28,movementBounds=null,aerialFloor=0,megapoleRoot=null;
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.5)); renderer.setSize(innerWidth,innerHeight); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.48; host.appendChild(renderer.domElement);
const ambient=new THREE.AmbientLight(0x7c321c,.9),hemi=new THREE.HemisphereLight(0x9edfff,0x2b0d08,1.15),key=new THREE.DirectionalLight(0xffc074,2.8),fill=new THREE.DirectionalLight(0x70dfff,1.9),glow=new THREE.PointLight(0xff5b20,145,340,1.5); key.position.set(-26,52,28); fill.position.set(34,30,-38); scene.add(ambient,hemi,key,fill,glow,key.target,fill.target);
function setStatus(s,p){status.textContent=s;if(Number.isFinite(p))bar.style.width=`${THREE.MathUtils.clamp(p,0,100)}%`}
async function decoder(){try{const m=await import('../vendor/meshopt_decoder.module.js');await m.MeshoptDecoder?.ready;return m.MeshoptDecoder||null}catch(e){console.warn(e);return null}}
function load(url,d){return new Promise((ok,no)=>{const l=new GLTFLoader();if(d)l.setMeshoptDecoder(d);l.load(url,ok,x=>{if(x.total)setStatus("FALLING INTO SILMARI'LLION MEGAPOLE",Math.min(99,x.loaded/x.total*100))},no)})}
function frame(root){root.rotation.y=Math.PI;root.updateMatrixWorld(true);let box=new THREE.Box3().setFromObject(root);if(box.isEmpty())return 0;let size=box.getSize(new THREE.Vector3()),max=Math.max(size.x,size.y,size.z);if(max<25){root.scale.multiplyScalar(120/max);root.updateMatrixWorld(true);box=new THREE.Box3().setFromObject(root);size=box.getSize(new THREE.Vector3())}const center=box.getCenter(new THREE.Vector3());root.position.sub(center);root.updateMatrixWorld(true);box=new THREE.Box3().setFromObject(root);size=box.getSize(new THREE.Vector3());let meshes=0;root.traverse(o=>{if(o.isMesh){meshes++;o.visible=true;o.frustumCulled=false;const ms=Array.isArray(o.material)?o.material:[o.material];ms.forEach(m=>{if(m){m.side=THREE.DoubleSide;if(m.map)m.map.colorSpace=THREE.SRGBColorSpace;m.needsUpdate=true}})}});const sphere=box.getBoundingSphere(new THREE.Sphere()),r=Math.max(sphere.radius,1),distance=(r/Math.sin(THREE.MathUtils.degToRad(camera.fov)/2))*.92,aerialHeight=THREE.MathUtils.clamp(size.y*.72,16,r*.9);aerialFloor=Math.max(2,-size.y*.1);camera.position.set(0,aerialHeight,distance);camera.near=.03;camera.far=Math.max(1200,distance+r*10);camera.updateProjectionMatrix();camera.lookAt(0,size.y*.12,0);camera.rotation.order='YXZ';yaw=camera.rotation.y;pitch=camera.rotation.x;movementBounds=new THREE.Box3(new THREE.Vector3(-size.x,aerialFloor,-size.z),new THREE.Vector3(size.x,Math.max(aerialHeight*2.4,size.y*1.5),Math.max(distance*1.25,size.z)));return meshes}
async function install(){setStatus('SWALLOWED BY DRAGON · AERIAL ENTRY',4);try{const g=await load('/assets/assets/models/SILMARI_LLION_MEGAPOLE_LUBIAK.glb?v=20260830-middle-drag-v2',await decoder());megapoleRoot=g.scene;megapoleRoot.name='SILMARI_LLION_MEGAPOLE';scene.add(megapoleRoot);const n=frame(megapoleRoot);if(!n)throw Error('no renderable mesh');setStatus(`AERIAL RIDE · MEGAPOLE OPEN · ${n} MESHES`,100);setTimeout(()=>{status.style.opacity='0';progress.style.opacity='0'},1200)}catch(e){console.error(e);setStatus('MEGAPOLE MODEL FAILED TO RENDER',100)}}
const keys=new Set();addEventListener('keydown',e=>keys.add(e.key.toLowerCase()));addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
let drag=null;renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());renderer.domElement.addEventListener('pointerdown',e=>{e.preventDefault();drag={x:e.clientX,y:e.clientY,button:e.button,rootY:megapoleRoot?.rotation.y||0,rootX:megapoleRoot?.rotation.x||0};renderer.domElement.setPointerCapture(e.pointerId)});
renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(drag.button===1&&megapoleRoot){megapoleRoot.rotation.y=drag.rootY+dx*.006;megapoleRoot.rotation.x=THREE.MathUtils.clamp(drag.rootX+dy*.0035,-.55,.55);megapoleRoot.updateMatrixWorld(true);return}yaw-=dx*.0042;pitch-=dy*.0032;pitch=THREE.MathUtils.clamp(pitch,-1.05,.72);drag.x=e.clientX;drag.y=e.clientY});
renderer.domElement.addEventListener('pointerup',()=>drag=null);renderer.domElement.addEventListener('pointercancel',()=>drag=null);renderer.domElement.addEventListener('auxclick',e=>{if(e.button===1)e.preventDefault()});renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();const f=new THREE.Vector3(Math.sin(yaw),0,-Math.cos(yaw));camera.position.addScaledVector(f,-Math.sign(e.deltaY)*2.6)},{passive:false});
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04),speed=12*dt,f=new THREE.Vector3(Math.sin(yaw),0,-Math.cos(yaw)),r=new THREE.Vector3(Math.cos(yaw),0,Math.sin(yaw));if(keys.has('w')||keys.has('arrowup'))camera.position.addScaledVector(f,speed);if(keys.has('s')||keys.has('arrowdown'))camera.position.addScaledVector(f,-speed);if(keys.has('a')||keys.has('arrowleft'))camera.position.addScaledVector(r,-speed);if(keys.has('d')||keys.has('arrowright'))camera.position.addScaledVector(r,speed);if(keys.has(' ')||keys.has('e'))camera.position.y+=speed;if(keys.has('shift')||keys.has('q'))camera.position.y-=speed;if(movementBounds)camera.position.clamp(movementBounds.min,movementBounds.max);camera.rotation.order='YXZ';camera.rotation.y=yaw;camera.rotation.x=pitch;renderer.render(scene,camera)}animate();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});install();