// ignore_for_file: avoid_web_libraries_in_flutter, deprecated_member_use

import 'dart:async';
import 'dart:convert';
import 'dart:html' as html;
import 'dart:ui_web' as ui_web;

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../core/app_config.dart';
import '../models/card_image_model.dart';
import '../providers/dj_who_player_provider.dart';

class WebGlCardCastleView extends StatefulWidget {
  const WebGlCardCastleView({required this.cards,required this.matchingCardIds,required this.focusedCardId,required this.shuffleSeed,required this.activeCategory,required this.fullscreenRequestId,required this.onCardSelected,required this.onCardOpened,required this.onFullscreenChanged,required this.onCategoriesRequested,required this.fallback,super.key});
  final List<CardImageModel> cards; final Set<String> matchingCardIds; final String? focusedCardId; final int shuffleSeed; final String activeCategory; final int fullscreenRequestId; final ValueChanged<String> onCardSelected; final Future<void> Function(String) onCardOpened; final ValueChanged<bool> onFullscreenChanged; final VoidCallback onCategoriesRequested; final Widget fallback;
  @override State<WebGlCardCastleView> createState()=>_WebGlCardCastleViewState();
}
class _WebGlCardCastleViewState extends State<WebGlCardCastleView>{
  late final String viewType; late final html.IFrameElement iframe; StreamSubscription<html.MessageEvent>? messages; StreamSubscription<html.Event>? frameLoads; Timer? cardOverlayReleaseTimer; DateTime? cardOverlayReleasedAt; DjWhoPlayerProvider? djWhoPlayer; late final bool isIos; bool rendererFailed=false,rendererReady=false,cardOverlayActive=false,djWhoSuspensionStarted=false,castleLoadingComplete=false;
  @override void initState(){super.initState();viewType='search-card-castle-${DateTime.now().microsecondsSinceEpoch}';final n=html.window.navigator;isIos=RegExp(r'iP(?:hone|ad|od)').hasMatch(n.userAgent)||(n.platform=='MacIntel'&&(n.maxTouchPoints??0)>1);final u=Uri.base.resolve('card_castle/card_castle_fast.html');iframe=html.IFrameElement()..id='search-card-castle-frame'..src=u.replace(queryParameters:{...u.queryParameters,'v':AppConfig.appBuildSha}).toString()..style.border='0'..style.width='100%'..style.height='100%'..style.display='block'..setAttribute('allow','fullscreen')..setAttribute('allowfullscreen','true')..setAttribute('popover','manual')..setAttribute('title','Three.js Search card castle');iframe.dataset['iosLoaderMode']=isIos?'draco-js-watchdog':'compressed-draco';ui_web.platformViewRegistry.registerViewFactory(viewType,(_)=>iframe);frameLoads=iframe.onLoad.listen((_){_sendState();});messages=html.window.onMessage.listen(_handleMessage);}
  @override void didChangeDependencies(){super.didChangeDependencies();if(djWhoSuspensionStarted)return;djWhoPlayer=context.read<DjWhoPlayerProvider>();djWhoSuspensionStarted=true;unawaited(djWhoPlayer!.suspendForCastleLoad());}
  @override void didUpdateWidget(covariant WebGlCardCastleView oldWidget){super.didUpdateWidget(oldWidget);if(!rendererReady)return;final cc=_cardFingerprint(oldWidget.cards)!=_cardFingerprint(widget.cards);final mc=!setEquals(oldWidget.matchingCardIds,widget.matchingCardIds);if(cc||mc||oldWidget.activeCategory!=widget.activeCategory||oldWidget.shuffleSeed!=widget.shuffleSeed){_sendState();}else if(oldWidget.focusedCardId!=widget.focusedCardId){_sendFocus();}if(oldWidget.fullscreenRequestId!=widget.fullscreenRequestId)_requestFullscreen();}
  @override void dispose(){_post({'type':'dispose'});frameLoads?.cancel();messages?.cancel();cardOverlayReleaseTimer?.cancel();_resumeDjWhoAfterCastleLoad();_setInAppFullscreen(false);super.dispose();}
  void _resumeDjWhoAfterCastleLoad(){if(!djWhoSuspensionStarted||castleLoadingComplete)return;castleLoadingComplete=true;final p=djWhoPlayer;if(p!=null)unawaited(p.resumeAfterCastleLoad());}
  void _openCardOverlay(String id){if(cardOverlayActive)return;cardOverlayActive=true;iframe.dataset['lastOpenedCardId']=id;_setInAppFullscreen(false);_setCardOverlayMode(true);unawaited(Future<void>.sync(()=>widget.onCardOpened(id)).whenComplete((){if(!mounted)return;cardOverlayActive=false;_setCardOverlayMode(false);}));}
  void _handleMessage(html.MessageEvent event){if(event.origin!=html.window.location.origin||event.data is! String)return;try{final d=jsonDecode(event.data! as String);if(d is! Map<String,dynamic>)return;iframe.dataset['lastBridgeMessage']=d['type']?.toString()??'';switch(d['type']){case 'rendererReady':rendererReady=true;_sendState();if(widget.fullscreenRequestId>0)_requestFullscreen();case 'castleLoadingComplete':_resumeDjWhoAfterCastleLoad();case 'rendererError':_resumeDjWhoAfterCastleLoad();if(mounted)setState(()=>rendererFailed=true);case 'cardSelected':final id=d['cardId'] as String?;if(id!=null){widget.onCardSelected(id);_openCardOverlay(id);}case 'cardLongPressed':break;case 'fullscreenFallbackRequested':_setInAppFullscreen(true);_post({'type':'setInAppFullscreen','active':true});case 'fullscreenFallbackExit':_setInAppFullscreen(false);_post({'type':'setInAppFullscreen','active':false});case 'fullscreenChanged':final a=d['active']==true;if(!a)_setInAppFullscreen(false);widget.onFullscreenChanged(a);case 'categoriesRequested':if(_suppressCategoriesAfterCardClose()){iframe.dataset['suppressedCategoryRequest']='ios-post-card-overlay';return;}_resumeDjWhoAfterCastleLoad();_setInAppFullscreen(false);widget.onFullscreenChanged(false);widget.onCategoriesRequested();}}on FormatException{/* Ignore malformed bridge messages. */}}
  void _sendState()=>_post({'type':'setCards','focusedCardId':widget.focusedCardId,'animateFocus':widget.focusedCardId!=null,'activeCategory':widget.activeCategory,'shuffleSeed':widget.shuffleSeed,'cards':widget.cards.map((c)=>{'id':c.id,'category':c.category,'question':c.question,'text':[c.question,c.answer].where((v)=>v.isNotEmpty).join(' '),'tags':c.tags,'metadata':{'author':c.author,'theme':c.theme,'emotion':c.emotion,'year':c.year},'isMatch':widget.matchingCardIds.contains(c.id),'rectoUrl':_castlePreviewUrl(c),'imagePath':_assetUrl(c.imagePath),'aspectRatio':c.aspectRatio}).toList()});
  void _sendFocus()=>_post({'type':'focusCard','cardId':widget.focusedCardId,'animate':true}); void _requestFullscreen(){if(rendererReady)_post({'type':'enterFullscreen'});}
  void _setInAppFullscreen(bool a){if(a){iframe.style..position='fixed'..left='0'..top='0'..width='100vw'..height='100vh'..zIndex='2147483647'..backgroundColor='#03070c';}else{iframe.style..position=''..left=''..top=''..width='100%'..height='100%'..zIndex=''..backgroundColor='';}}
  void _setCardOverlayMode(bool a){cardOverlayReleaseTimer?.cancel();iframe.dataset['cardOverlayActive']=a.toString();if(a){iframe.style..pointerEvents='none'..visibility='hidden';iframe.setAttribute('aria-hidden','true');return;}iframe.style.visibility='';iframe.attributes.remove('aria-hidden');if(!isIos){iframe.style.pointerEvents='';return;}cardOverlayReleasedAt=DateTime.now();iframe.style.pointerEvents='none';cardOverlayReleaseTimer=Timer(const Duration(milliseconds:520),(){if(mounted&&!cardOverlayActive)iframe.style.pointerEvents='';});}
  bool _suppressCategoriesAfterCardClose(){if(cardOverlayActive)return true;final r=cardOverlayReleasedAt;if(!isIos||r==null)return false;return DateTime.now().difference(r)<const Duration(milliseconds:850);}
  String _castlePreviewUrl(CardImageModel c){final m=RegExp(r'^final-84-(\d{1,2})$').firstMatch(c.id);if(m!=null){final n=int.tryParse(m.group(1)??'');if(n!=null&&n>=1&&n<=84)return Uri.base.resolve('assets/share-previews/UNO-${n.toString().padLeft(3,'0')}.jpg').toString();}return _assetUrl(c.imagePath);} String _cardFingerprint(List<CardImageModel> c)=>c.map((x)=>'${x.id}\u001f${x.imagePath}\u001f${x.aspectRatio}').join('\u001e'); String _assetUrl(String s)=>s.startsWith('assets/')?Uri.base.resolve(s).toString():s; void _post(Map<String,dynamic>d)=>iframe.contentWindow?.postMessage(jsonEncode(d),Uri.base.origin);
  @override Widget build(BuildContext context){if(rendererFailed)return Stack(fit:StackFit.expand,children:[widget.fallback,const Positioned(left:12,top:12,child:_FallbackNotice()),Positioned(left:12,bottom:12,child:OutlinedButton.icon(key:const ValueKey('castle-back-to-categories'),onPressed:widget.onCategoriesRequested,icon:const Icon(Icons.arrow_back_rounded),label:const Text('CATEGORIES')))]);return HtmlElementView(viewType:viewType);}
}
class _FallbackNotice extends StatelessWidget{const _FallbackNotice();@override Widget build(BuildContext context)=>DecoratedBox(decoration:BoxDecoration(color:const Color(0xDD090806),borderRadius:BorderRadius.circular(12),border:Border.all(color:const Color(0xFFFFC928))),child:const Padding(padding:EdgeInsets.all(10),child:Text('3D Castle unavailable. Using the compatibility card view.',style:TextStyle(color:Color(0xFFFFC928)))));}
