import 'dart:convert';
import 'dart:io';

import 'package:uno_chanson_2/core/app_constants.dart';
import 'package:uno_chanson_2/services/card_share_identity.dart';

const _defaultPublicBase = 'https://dupuis-scot.github.io/CHANSON-A-REPONDRE-UNO/';

String buildCanonicalShareHtml({required Uri publicBase,required String cardId,required String shareSlug,required String title,required String imagePath,String? previewImagePath,String? transcription,int? imageWidth,int? imageHeight}) {
  final root=publicBase.pathSegments.where((s)=>s.isNotEmpty); final shareUrl=publicBase.replace(pathSegments:[...root,'share',shareSlug,'']); final deepLink=publicBase.replace(fragment:'/cards/$cardId'); final socialImagePath=previewImagePath??imagePath; final imageUrl=publicBase.replace(pathSegments:[...root,'assets',...socialImagePath.split('/')]); final mime=_imageMimeType(socialImagePath); final dimensions=StringBuffer();
  if(imageWidth!=null&&imageWidth>0) dimensions.writeln('  <meta property="og:image:width" content="$imageWidth">'); if(imageHeight!=null&&imageHeight>0) dimensions.writeln('  <meta property="og:image:height" content="$imageHeight">');
  final t=_html(title),id=_html(cardId),share=_html(shareUrl.toString()),deep=_html(deepLink.toString()),image=_html(imageUrl.toString()),type=_html(mime),text=_html(transcription?.trim()??''),description=_html('Open $title.'),deepJson=jsonEncode(deepLink.toString());
  return '''<!doctype html><html lang="fr"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>$t</title><meta name="description" content="$description"><meta name="card-id" content="$id"><meta property="og:type" content="website"><meta property="og:site_name" content="Chanson à Répondre"><meta property="og:title" content="$t"><meta property="og:description" content="$description"><meta property="og:image" content="$image"><meta property="og:image:url" content="$image"><meta property="og:image:secure_url" content="$image"><meta property="og:image:type" content="$type"><meta property="og:image:alt" content="$t">$dimensions<meta property="og:url" content="$share"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="$t"><meta name="twitter:description" content="$description"><meta name="twitter:image" content="$image"><meta name="twitter:image:alt" content="$t"><link rel="canonical" href="$share"></head><body><main><h1>$t</h1><p>Card ID: <span id="card-id">$id</span></p><figure><img id="card-image" src="$image" alt="$t" style="max-width:min(100%,600px);height:auto"></figure><section><h2>Card transcription</h2><pre id="card-transcription" style="white-space:pre-wrap">${text.isEmpty?'No static transcription is embedded for this card yet. Use the card image above or the in-app transcription.':text}</pre></section><p><a href="$deep">Open this card in Chanson à Répondre</a></p></main><script>window.location.replace($deepJson);</script></body></html>''';
}

String buildLegacyRedirectHtml({required Uri publicBase,required String legacySlug,required String canonicalSlug,required String title,required String imagePath}) {
  final root=publicBase.pathSegments.where((s)=>s.isNotEmpty),canonical=publicBase.replace(pathSegments:[...root,'share',canonicalSlug,'']),image=publicBase.replace(pathSegments:[...root,'assets',...imagePath.split('/')]); final c=_html(canonical.toString()),i=_html(image.toString()),t=_html(title),json=jsonEncode(canonical.toString());
  return '''<!doctype html><html><head><meta charset="UTF-8"><title>$t</title><meta property="og:title" content="$t"><meta property="og:image" content="$i"><meta property="og:url" content="$c"><link rel="canonical" href="$c"></head><body><a href="$c">Open canonical card link</a><script>window.location.replace($json);</script></body></html>''';
}

Future<void> main(List<String> arguments) async {
  final o=_parseOptions(arguments),catalog=o['catalog']??AppConstants.cardsAsset,brio=o['brio']??AppConstants.brioDeckAsset,build=o['build-dir']??'build/web',base=Uri.parse(o['public-base']??_defaultPublicBase);
  final cards=< _ShareCard>[...await _loadUno(catalog),...await _loadBrio(brio),..._loadHp()]; final slugs=cards.map((c)=>CardShareIdentity.canonicalSlugFor(cardId:c.id,deckId:c.deckId)).toSet(); if(cards.length!=104||slugs.length!=104) throw FormatException('Expected 104 built-in cards with unique canonical share slugs; found ${cards.length} cards and ${slugs.length} slugs.');
  final root=Directory('$build/share'); await root.create(recursive:true); var legacyCount=0;
  for(final c in cards){final slug=CardShareIdentity.canonicalSlugFor(cardId:c.id,deckId:c.deckId),title=CardShareIdentity.titleFor(cardId:c.id,deckId:c.deckId,deckName:c.deckName); final page=File('${root.path}/$slug/index.html'); await page.parent.create(recursive:true); await page.writeAsString(buildCanonicalShareHtml(publicBase:base,cardId:c.id,shareSlug:slug,title:title,imagePath:c.imagePath,previewImagePath:c.previewImagePath,transcription:c.transcription,imageWidth:c.imageWidth,imageHeight:c.imageHeight)); final legacy=CardShareIdentity.legacySlugFor(cardId:c.id,deckId:c.deckId); if(legacy!=null&&legacy!=slug){final p=File('${root.path}/$legacy/index.html');await p.parent.create(recursive:true);await p.writeAsString(buildLegacyRedirectHtml(publicBase:base,legacySlug:legacy,canonicalSlug:slug,title:title,imagePath:c.imagePath));legacyCount++;}}
  stdout.writeln('Generated ${cards.length} canonical share pages and $legacyCount legacy redirects.');
}

Future<List<_ShareCard>> _loadUno(String path) async {final d=jsonDecode(await File(path).readAsString()) as Map<String,dynamic>,deck=(d['decks'] as List).whereType<Map<String,dynamic>>().firstWhere((x)=>x['id']==AppConstants.productionDeckId); final cards=(deck['cards'] as List).whereType<Map<String,dynamic>>().map((c)=>_ShareCard(id:c['id']??'',deckId:AppConstants.productionDeckId,deckName:deck['name']??'Chanson à répondre UNO',imagePath:(c['path']??c['image'])??'',transcription:_shareTranscriptionFromJson(c),imageWidth:(c['imageWidth'] as num?)?.toInt(),imageHeight:(c['imageHeight'] as num?)?.toInt())).toList();if(cards.length!=84)throw const FormatException('Expected 84 unique UNO cards.');return cards;}
Future<List<_ShareCard>> _loadBrio(String path) async {final d=jsonDecode(await File(path).readAsString()) as Map<String,dynamic>;final cards=(d['cards'] as List).whereType<Map<String,dynamic>>().map((c){final id=c['id'] as String? ??'',slug=CardShareIdentity.canonicalSlugFor(cardId:id,deckId:AppConstants.brioDeckId);return _ShareCard(id:id,deckId:AppConstants.brioDeckId,deckName:d['name']??'Chanson à répondre BRIO',imagePath:(c['path']??c['image'])??'',previewImagePath:'share-previews/$slug.jpg',transcription:_shareTranscriptionFromJson(c),imageWidth:600,imageHeight:900);}).toList();if(cards.length!=16)throw const FormatException('Expected 16 unique BRIO cards.');return cards;}
List<_ShareCard> _loadHp(){const paths=['hp/ChatGPT Image Aug 22, 2026, 10_59_05 AM.png','hp/ChatGPT Image Aug 22, 2026, 11_00_51 AM.png','hp/ChatGPT Image Aug 22, 2026, 11_08_07 AM.png','hp/ChatGPT Image Aug 22, 2026, 11_12_32 AM.png'];return [for(var i=0;i<paths.length;i++) _ShareCard(id:'hp-${(i+1).toString().padLeft(3,'0')}',deckId:AppConstants.hpDeckId,deckName:'Chanson à répondre HP',imagePath:paths[i],previewImagePath:'share-previews/HP-${(i+1).toString().padLeft(3,'0')}.jpg',imageWidth:600,imageHeight:900)];}
String? _shareTranscriptionFromJson(Map<String,dynamic> c){for(final k in const ['cleanedTranscription','transcription']){final v=c[k];if(v is String&&v.trim().isNotEmpty)return v.trim();}final p=<String>[];for(final k in const ['question','answer']){final v=c[k];if(v is String&&v.trim().isNotEmpty)p.add(v.trim());}return p.isEmpty?null:p.join('\n\n');}
Map<String,String> _parseOptions(List<String> a){final r=<String,String>{};for(var i=0;i<a.length;i+=2){if(i+1>=a.length||!a[i].startsWith('--'))throw const FormatException('Options must be --name value pairs.');r[a[i].substring(2)]=a[i+1];}return r;}
String _imageMimeType(String p){p=p.toLowerCase();if(p.endsWith('.png'))return'image/png';if(p.endsWith('.webp'))return'image/webp';if(p.endsWith('.gif'))return'image/gif';return'image/jpeg';}
String _html(String v)=>v.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
class _ShareCard{const _ShareCard({required this.id,required this.deckId,required this.deckName,required this.imagePath,this.previewImagePath,this.transcription,this.imageWidth,this.imageHeight});final String id,deckId,deckName,imagePath;final String? previewImagePath,transcription;final int? imageWidth,imageHeight;}
