create table if not exists public.social_preview_share_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  share_kind text not null default 'social_preview'
);

alter table public.social_preview_share_events disable row level security;
revoke all on table public.social_preview_share_events from public, anon, authenticated;
grant select, insert on table public.social_preview_share_events to anon, authenticated;
grant usage, select on sequence public.social_preview_share_events_id_seq to anon, authenticated;

create or replace function public.record_social_preview_share(p_share_kind text default 'social_preview')
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare v_count bigint;
begin
  insert into public.social_preview_share_events(share_kind)
  values (left(coalesce(nullif(p_share_kind,''),'social_preview'), 64));
  select count(*) into v_count from public.social_preview_share_events;
  return v_count;
end;
$$;

create or replace function public.get_social_preview_share_count()
returns bigint
language sql
security invoker
set search_path = public
stable
as $$
  select count(*)::bigint from public.social_preview_share_events;
$$;

revoke all on function public.record_social_preview_share(text) from public;
revoke all on function public.get_social_preview_share_count() from public;
grant execute on function public.record_social_preview_share(text) to anon, authenticated;
grant execute on function public.get_social_preview_share_count() to anon, authenticated;
