import * as THREE from 'three';
import { GLTFLoader } from './vendor/GLTFLoader.js';
import { DRACOLoader } from 'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/loaders/DRACOLoader.js';

const dealers=new Map();
const MODEL_REVISION='play-jester-face-user-20260901-v12';
const MODEL_URL=new URL(`assets/assets/models/play_jester_rigged.glb?rev=${MODEL_REVISION}`,document.baseURI).href;
// PLAY jester: another 180 degrees from the previous 90-degree heading = 270 degrees around Y.
const MODEL_FACING_Y=3*Math.PI/2;
const DRACO_PATH='https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/libs/draco/';
const clamp01=v=>Math.max(0,Math.min(1,v));
const smooth=v=>{const t=clamp01(v);return t*t*(3-2*t)};
function disposeMaterial(m){if(!m)return;for(const v of Object.values(m))if(v?.isTexture)v.dispose();m.dispose?.()}
function disposeObject(root){root?.traverse(o=>{o.geometry?.dispose?.();if(Array.isArray(o.material))o.material.forEach(disposeMaterial);else disposeMaterial(o.material)})}
function makeCard(){const edge=new THREE.MeshStandardMaterial({color:0xe8d9b8,roughness:.54});const f=new THREE.MeshStandardMaterial({color:0x22100f});const b=new THREE.MeshStandardMaterial({color:0x77151d});const card=new THREE.Mesh(new THREE.BoxGeometry(.82,1.24,.04),[edge,edge,edge,edge,f,b]);card.visible=false;card.userData={edgeMaterial:edge};return card}
function loadTexture(url){return new Promise((resolve,reject)=>new THREE.TextureLoader().load(url,t=>{t.colorSpace=THREE.SRGBColorSpace;resolve(t)},undefined,reject))}
class JesterDealer{
constructor(host,quality='medium'){this.host=host;this.quality=quality;this.disposed=false;this.visible=true;this.frame=0;this.animation=null;this.model=null;host.dataset.dealerStatus='loading';host.dataset.modelRevision=MODEL_REVISION;host.dataset.poseMode='static-visual-fallback';host.dataset.modelFacingAngle=String(MODEL_FACING_Y);this.status=document.createElement('div');this.status.style.cssText='position:absolute;inset:0;display:flex;align-items:center;justify-content:center;z-index:22;color:#f0c56b;background:rgba(5,3,2,.22);font:600 14px Georgia,serif;pointer-events:none;opacity:0';host.appendChild(this.status);this.scene=new THREE.Scene();this.root=new THREE.Group();this.root.rotation.y=MODEL_FACING_Y;this.scene.add(this.root);this.camera=new THREE.PerspectiveCamera(32,1,.05,100);this.renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});this.renderer.setClearColor(0,0);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.1;this.renderer.domElement.dataset.renderer='three.js-gltf';this.renderer.domElement.style.cssText='position:absolute;inset:0;width:100%;height:100%;display:block;pointer-events:none';host.insertBefore(this.renderer.domElement,this.status);this.scene.add(new THREE.HemisphereLight(0xffe4bd,0x17101b,2.4));const key=new THREE.DirectionalLight(0xffbf79,4);key.position.set(-4,6,7);this.scene.add(key);const fill=new THREE.DirectionalLight(0xc9ddff,2.2);fill.position.set(5,2,5);this.scene.add(fill);this.card=makeCard();this.scene.add(this.card);this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(host);this.intersectionObserver=new IntersectionObserver(([e])=>{this.visible=e.isIntersecting;if(this.visible)this.resume();else this.pause()});this.intersectionObserver.observe(host);document.addEventListener('visibilitychange',this.onVisibilityChange);this.resize();this.loadModel()}
showError(m){this.status.textContent=m;this.status.style.opacity='1'} clearError(){this.status.style.opacity='0';this.status.textContent=''}
loadModel(){this.host.dataset.modelAsset=MODEL_URL;const manager=new THREE.LoadingManager();const draco=new DRACOLoader(manager);draco.setDecoderPath(DRACO_PATH);draco.setWorkerLimit(/iP(?:hone|ad|od)/.test(navigator.userAgent)?1:2);const loader=new GLTFLoader(manager);loader.setDRACOLoader(draco);loader.load(MODEL_URL,gltf=>{draco.dispose();if(this.disposed)return;const source=gltf.scene;source.updateMatrixWorld(true);const visual=new THREE.Group();let count=0;source.traverse(o=>{if(!(o.isMesh||o.isSkinnedMesh))return;if(/string|marionette|control[_ -]?line/i.test(o.name))return;const g=o.geometry?.clone();if(!g)return;const mats=(Array.isArray(o.material)?o.material:[o.material]).map(m=>{const c=m?.clone?.()||new THREE.MeshStandardMaterial({color:0xffffff});c.side=THREE.DoubleSide;c.transparent=false;c.opacity=1;c.depthWrite=true;c.visible=true;c.needsUpdate=true;return c});const mesh=new THREE.Mesh(g,Array.isArray(o.material)?mats:mats[0]);o.updateWorldMatrix(true,false);mesh.matrix.copy(o.matrixWorld);mesh.matrix.decompose(mesh.position,mesh.quaternion,mesh.scale);mesh.frustumCulled=false;mesh.renderOrder=5;visual.add(mesh);count++});if(!count){this.host.dataset.dealerStatus='failed';this.showError('3D jester has no renderable mesh.');return}this.model=visual;this.root.add(visual);this.frameModel();this.host.dataset.visualMeshCount=String(count);this.host.dataset.dealerStatus='ready';this.host.dataset.renderMode='static-mesh-from-bind-geometry';this.clearError();this.resume()},e=>{if(e?.total)this.host.dataset.modelProgress=String(Math.round(e.loaded/e.total*100))},err=>{draco.dispose();this.host.dataset.dealerStatus='failed';this.host.dataset.modelError=String(err?.message||err);this.showError('3D jester failed to load.');console.error('PLAY Jester load failed',err)})}
frameModel(){if(!this.model)return;this.model.updateMatrixWorld(true);let box=new THREE.Box3().setFromObject(this.model);if(box.isEmpty())return;let size=box.getSize(new THREE.Vector3());const s=4.8/Math.max(size.y,.001);this.model.scale.setScalar(s);this.model.updateMatrixWorld(true);box=new THREE.Box3().setFromObject(this.model);let center=box.getCenter(new THREE.Vector3());this.model.position.sub(center);this.model.position.y+=.25;this.model.updateMatrixWorld(true);box=new THREE.Box3().setFromObject(this.model);size=box.getSize(new THREE.Vector3());center=box.getCenter(new THREE.Vector3());const w=Math.max(this.host.clientWidth,1),h=Math.max(this.host.clientHeight,1);this.camera.aspect=w/h;this.camera.fov=w<720?36:32;const vf=THREE.MathUtils.degToRad(this.camera.fov),hf=2*Math.atan(Math.tan(vf/2)*this.camera.aspect);const d=Math.max(size.y*.56/Math.tan(vf/2),size.x*.56/Math.tan(hf/2),3.4);this.camera.position.set(center.x,center.y,d);this.camera.lookAt(center);this.camera.updateProjectionMatrix();this.host.dataset.modelBounds=`${size.x.toFixed(2)},${size.y.toFixed(2)},${size.z.toFixed(2)}`}
resize(){const w=Math.max(this.host.clientWidth,1),h=Math.max(this.host.clientHeight,1);this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,this.quality==='high'?1.6:this.quality==='low'?.8:1.2));this.renderer.setSize(w,h,false);if(this.model)this.frameModel();else{this.camera.aspect=w/h;this.camera.position.set(0,.2,6);this.camera.lookAt(0,.2,0);this.camera.updateProjectionMatrix()}}
async updateCardTextures(recto,verso){this.host.dataset.cardTexture='loading';try{const[a,b]=await Promise.all([loadTexture(recto),loadTexture(verso||recto)]);const front=new THREE.MeshStandardMaterial({map:a,roughness:.5});const back=new THREE.MeshStandardMaterial({map:b,roughness:.54});const e=this.card.userData.edgeMaterial;this.card.material=[e,e,e,e,front,back];this.host.dataset.cardTexture='ready'}catch(error){this.host.dataset.cardTexture='failed';console.error('PLAY card texture failed',error)}}
startDeal(verso,recto,receive=false){if(this.animation||!this.model)return false;this.updateCardTextures(recto||verso,verso);this.animation={started:performance.now(),duration:receive?2300:3600,receive};this.host.dataset.dealerAnimation=receive?'receive':'deal';this.card.scale.setScalar(.92);this.card.visible=true;return true}
update(){if(!this.animation)return;const t=clamp01((performance.now()-this.animation.started)/this.animation.duration);const p=smooth(t),gesture=Math.sin(Math.PI*p);this.root.rotation.y=MODEL_FACING_Y+(this.animation.receive?-.16:.14)*gesture;this.root.rotation.z=(this.animation.receive?.035:-.025)*gesture;this.root.position.set((this.animation.receive?-.12:.1)*gesture,.08*gesture,0);if(this.animation.receive){const arc=Math.sin(Math.PI*p);this.card.position.set(.05-1.2*p,-2.05+1.55*p+.32*arc,2.45-.35*p);this.card.rotation.set(-.08,-.3*p,.12-.2*p)}else{const flip=smooth((t-.28)/.34);const arc=Math.sin(Math.PI*p);this.card.position.set(-1.15+1.15*p,-.5-1.55*p+.28*arc,2.1+.35*p);this.card.rotation.set(-.08,Math.PI*(1-flip),-.12*(1-p))}if(t>=1){this.animation=null;this.card.visible=false;this.root.position.set(0,0,0);this.root.rotation.set(0,MODEL_FACING_Y,0);this.host.dataset.dealerAnimation='idle'}}
render=()=>{if(this.disposed||!this.visible||document.hidden)return;this.update();this.renderer.render(this.scene,this.camera);this.frame=requestAnimationFrame(this.render)};resume(){if(!this.disposed&&this.visible&&!this.frame&&!document.hidden)this.frame=requestAnimationFrame(this.render)} pause(){if(this.frame)cancelAnimationFrame(this.frame);this.frame=0} onVisibilityChange=()=>document.hidden?this.pause():this.resume();setQuality(v){this.quality=['low','medium','high'].includes(v)?v:'medium';this.resize()}dispose(){this.disposed=true;this.pause();this.resizeObserver?.disconnect();this.intersectionObserver?.disconnect();document.removeEventListener('visibilitychange',this.onVisibilityChange);disposeObject(this.model);disposeObject(this.card);this.renderer.dispose();this.renderer.domElement.remove();this.status.remove()}}
window.puppetDealerCreate=async(id,containerOrQuality,quality='medium')=>{const suppliedContainer=containerOrQuality&&typeof containerOrQuality==='object'&&containerOrQuality.nodeType===1?containerOrQuality:null;if(!suppliedContainer&&typeof containerOrQuality==='string')quality=containerOrQuality;let container=suppliedContainer||document.getElementById(id);for(let frame=0;id&&!container&&frame<120;frame++){await new Promise(resolve=>requestAnimationFrame(resolve));container=document.getElementById(id)}if(!id||!container){console.error('PLAY Jester container not found after mount wait',{id});return false}dealers.get(id)?.dispose();const d=new JesterDealer(container,quality);dealers.set(id,d);return true};window.puppetDealerDeal=(id,verso,recto)=>dealers.get(id)?.startDeal(verso,recto,false)??false;window.puppetDealerReceive=(id,card)=>dealers.get(id)?.startDeal(card,card,true)??false;window.puppetDealerSetQuality=(id,q)=>dealers.get(id)?.setQuality(q);window.puppetDealerDestroy=id=>{dealers.get(id)?.dispose();dealers.delete(id)};