import * as THREE from 'three';
import{GLTFLoader}from'./vendor/GLTFLoader.js';
const MODEL_FACING_Y=-Math.PI/2,JESTER_MODEL=new URL('assets/assets/models/transcription_jester_rigged.glb',document.baseURI).href,PUPPET_CANVAS_ID='transcription-jester-puppet-canvas',HP=Object.freeze({'hp-001':'assets/hp/ChatGPT Image Aug 22, 2026, 10_59_05 AM.png','hp-002':'assets/hp/ChatGPT Image Aug 22, 2026, 11_00_51 AM.png','hp-003':'assets/hp/ChatGPT Image Aug 22, 2026, 11_08_07 AM.png','hp-004':'assets/hp/ChatGPT Image Aug 22, 2026, 11_12_32 AM.png'});let puppet=null,pendingCard=null;
const abs=p=>{try{return p?new URL(p,document.baseURI).href:null}catch(_){return null}},uniq=a=>[...new Set(a.filter(Boolean))],clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),norm=n=>String(n||'').toLowerCase().replace(/[^a-z0-9]/g,'');
function stageRect(){const m=matchMedia('(max-width: 759px)').matches,w=innerWidth,h=innerHeight,sw=m?Math.min(w*.96,720):Math.min(w*.78,1040),sh=m?Math.min(h*.72,760):Math.min(h*.82,900);return{left:(w-sw)/2,top:m?Math.max(12,h*.025):Math.max(8,h*.015),width:sw,height:sh}}
function cardPath(c){if(!c)return'';const id=String(c.cardId||'').trim().toLowerCase();return HP[id]||String(c.imagePath||'').trim()}
function generated(id){id=String(id||'').trim();const m=/^final-84-(\d{2})$/i.exec(id);if(m)return`share-previews/UNO-${Number(m[1]).toString().padStart(3,'0')}.jpg`;if(/^(hp|brio)-\d+$/i.test(id))return`share-previews/${id.toUpperCase()}.jpg`;return''}
function candidates(c){const raw=cardPath(c),out=[];if(raw){if(/^(data:|blob:|https?:)/i.test(raw))out.push(abs(raw));else{const n=raw.replace(/^\/+/, '');if(n.startsWith('assets/assets/'))out.push(abs(n));else if(n.startsWith('share-previews/'))out.push(abs(`assets/${n}`),abs(n));else if(n.startsWith('assets/'))out.push(abs(`assets/${n}`),abs(n));else out.push(abs(`assets/${n}`),abs(n));}}const f=generated(c?.cardId);if(f)out.push(abs(`assets/${f}`),abs(f));return uniq(out)}
function browseHash(id){return`#/cards?focus=${encodeURIComponent(String(id||'').trim())}`}
function legacyCanvases(){return[...document.querySelectorAll('canvas[data-transcription-jester-canvas="true"]')].filter(e=>e.id!==PUPPET_CANVAS_ID)}
function setLegacyVisible(v){for(const e of legacyCanvases())e.style.visibility=v?'visible':'hidden'}
function suppressLegacyPreview(){const e=document.getElementById('transcription-jester-mode-card-preview');if(e){e.style.display='none';e.style.visibility='hidden';e.style.pointerEvents='none'}}
function disposeMaterial(m){if(!m)return;for(const v of Object.values(m))if(v?.isTexture)v.dispose();m.dispose?.()}
function disposeObject(r){r?.traverse(o=>{o.geometry?.dispose?.();Array.isArray(o.material)?o.material.forEach(disposeMaterial):disposeMaterial(o.material)})}
function choose(bs,tests){for(const t of tests){const b=bs.find(x=>t(norm(x.name)));if(b)return b}return null}
function discover(m){const bs=[];m.traverse(o=>{if(o.isBone)bs.push(o)});const all=(...p)=>n=>p.every(x=>n.includes(x)),ends=(...p)=>n=>p.some(x=>n.endsWith(x)),exact=(...p)=>n=>p.includes(n);return{all:bs,head:choose(bs,[ends('head'),all('head')]),chest:choose(bs,[all('upperchest'),all('spine2'),all('chest'),all('spine1'),all('spine')]),hips:choose(bs,[ends('hips','pelvis'),all('hip'),all('pelvis')]),leftUpperArm:choose(bs,[all('left','upperarm'),all('left','arm'),ends('upperarml','arml')]),rightUpperArm:choose(bs,[all('right','upperarm'),all('right','arm'),ends('upperarmr','armr')]),leftForeArm:choose(bs,[all('left','forearm'),all('left','lowerarm'),ends('forearml','lowerarml')]),rightForeArm:choose(bs,[all('right','forearm'),all('right','lowerarm'),ends('forearmr','lowerarmr')]),leftHand:choose(bs,[exact('lefthand','handl','lhand','mixamoriglefthand'),all('left','hand'),ends('handl','lefthand')]),rightHand:choose(bs,[exact('righthand','handr','rhand','mixamorigrighthand'),all('right','hand'),ends('handr','righthand')]),leftUpperLeg:choose(bs,[all('left','upleg'),all('left','upperleg'),all('left','thigh'),ends('uplegl','thighl')]),rightUpperLeg:choose(bs,[all('right','upleg'),all('right','upperleg'),all('right','thigh'),ends('uplegr','thighr')]),leftLowerLeg:choose(bs,[all('left','leg'),all('left','calf'),all('left','shin'),ends('legl','calfl')]),rightLowerLeg:choose(bs,[all('right','leg'),all('right','calf'),all('right','shin'),ends('legr','calfr')]),leftFoot:choose(bs,[all('left','foot'),all('left','ankle'),ends('footl')]),rightFoot:choose(bs,[all('right','foot'),all('right','ankle'),ends('footr')])}}
function uiTarget(t){return t instanceof Element&&!!t.closest('button,a,input,textarea,select,[role="button"],[role="link"]')}
class TranscriptionPuppet{
constructor(){this.disposed=false;this.frame=0;this.drags=new Map;this.rest=new Map;this.serial=0;this.selectedCard=pendingCard;this.hp=new THREE.Vector3;this.hq=new THREE.Quaternion;this.cq=new THREE.Quaternion;this.ndc=new THREE.Vector2;this.ray=new THREE.Raycaster;this.scene=new THREE.Scene;this.camera=new THREE.PerspectiveCamera(34,1,.01,200);this.renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});this.renderer.setClearColor(0,0);this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.45;this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.4));this.canvas=this.renderer.domElement;this.canvas.id=PUPPET_CANVAS_ID;Object.assign(this.canvas.dataset,{transcriptionJesterCanvas:'true',transcriptionPuppet:'true',puppetInteraction:'full-body-360-card-hit',puppetCardAttachment:'left-hand'});this.canvas.setAttribute('aria-hidden','true');Object.assign(this.canvas.style,{display:'block',position:'fixed',pointerEvents:'none',background:'transparent',zIndex:'2',opacity:'1',filter:'drop-shadow(0 18px 24px rgba(0,0,0,.78))',transform:'translateZ(0)'});document.body.appendChild(this.canvas);suppressLegacyPreview();this.pivot=new THREE.Group;this.pivot.rotation.y=MODEL_FACING_Y;this.scene.add(this.pivot);this.scene.add(new THREE.HemisphereLight(0xffe5bd,0x160607,3.8));const k=new THREE.DirectionalLight(0xffb35b,6.8);k.position.set(-3.2,5.5,6.2);this.scene.add(k);const f=new THREE.DirectionalLight(0xffffff,2.4);f.position.set(3.5,2.2,5.5);this.scene.add(f);const r=new THREE.DirectionalLight(0xc51e16,3.6);r.position.set(4.5,3.5,-2.5);this.scene.add(r);this.onResize=()=>this.resize();this.onDown=e=>this.pointerDown(e);this.onMove=e=>this.pointerMove(e);this.onUp=e=>this.pointerUp(e);addEventListener('resize',this.onResize);addEventListener('orientationchange',this.onResize);addEventListener('pointerdown',this.onDown,true);addEventListener('pointermove',this.onMove,true);addEventListener('pointerup',this.onUp,true);addEventListener('pointercancel',this.onUp,true);this.resize();this.load()}
load(){new GLTFLoader().load(JESTER_MODEL,g=>{if(this.disposed)return disposeObject(g.scene);this.model=g.scene;this.model.traverse(o=>{o.visible=true;if(!o.isMesh)return;if(!o.geometry.getAttribute('normal'))o.geometry.computeVertexNormals();(Array.isArray(o.material)?o.material:[o.material]).filter(Boolean).forEach(m=>{m.side=THREE.DoubleSide;m.transparent=false;m.opacity=1;m.depthWrite=true;m.needsUpdate=true})});this.model.updateMatrixWorld(true);const b=new THREE.Box3().setFromObject(this.model),s=b.getSize(new THREE.Vector3),c=b.getCenter(new THREE.Vector3),mx=Math.max(s.x,s.y,s.z,.001);this.model.position.sub(c);this.model.scale.setScalar(5.1/mx);this.model.position.set(0,0,0);this.pivot.add(this.model);if(g.animations?.length){this.mixer=new THREE.AnimationMixer(this.model);const clip=g.animations.find(x=>/idle|breath|stand/i.test(x.name))||g.animations[0],a=this.mixer.clipAction(clip);a.reset().play();this.mixer.setTime(Math.min(clip.duration*.16,.35));a.paused=true}this.bones=discover(this.model);this.held=this.bones.leftHand||this.bones.leftForeArm||this.bones.leftUpperArm||null;for(const b of this.bones.all)this.rest.set(b,b.rotation.clone());this.fit();this.attachCard();this.updateCard();Object.assign(this.canvas.dataset,{puppetBones:String(this.bones.all.length),puppetHeldBone:this.held?.name||'',puppetReady:'true'});this.resume()},undefined,e=>{this.canvas.dataset.puppetReady='failed';this.canvas.dataset.puppetError=String(e?.message||e)})}
bounds(){if(!this.model)return null;this.pivot.updateMatrixWorld(true);return new THREE.Box3().setFromObject(this.pivot)}
fit(){const b=this.bounds();if(!b)return;const s=b.getSize(new THREE.Vector3),t=b.getCenter(new THREE.Vector3),vf=THREE.MathUtils.degToRad(this.camera.fov),hf=2*Math.atan(Math.tan(vf/2)*Math.max(this.camera.aspect,.2)),vd=(Math.max(s.y*1.08,.5)*.5)/Math.tan(vf*.5),hd=(Math.max(s.x*1.18,.5)*.5)/Math.tan(Math.max(hf,.2)*.5),d=Math.max(vd,hd,4.8)*1.12;this.camera.position.set(t.x,t.y,t.z+d);this.camera.near=Math.max(.01,d/100);this.camera.far=Math.max(100,d*20);this.camera.lookAt(t);this.camera.updateProjectionMatrix()}
createCard(){if(this.card){this.scene.remove(this.card);disposeObject(this.card)}const a=new THREE.Group;a.name='JesterHeldCard';a.add(new THREE.Mesh(new THREE.BoxGeometry(.76,1.14,.055),new THREE.MeshStandardMaterial({color:0x1c0e08,roughness:.68,metalness:.08})));const face=new THREE.Mesh(new THREE.PlaneGeometry(.72,1.08),new THREE.MeshBasicMaterial({color:0x7b241d,side:THREE.DoubleSide,toneMapped:false,depthTest:false,depthWrite:false}));face.name='JesterHeldCardFace';face.position.z=.031;face.renderOrder=100;a.add(face);this.card=a;this.face=face;this.scene.add(a)}
updateCard(){if(!this.card||!this.held||!this.model)return;this.pivot.updateMatrixWorld(true);this.held.updateWorldMatrix(true,false);this.held.getWorldPosition(this.hp);this.held.getWorldQuaternion(this.hq);this.card.position.copy(this.hp).add(new THREE.Vector3(.06,-.03,.13).applyQuaternion(this.hq));this.card.quaternion.copy(this.hq);const m=new THREE.Matrix4().lookAt(this.card.position,this.camera.position,this.camera.up);this.cq.setFromRotationMatrix(m);this.card.quaternion.slerp(this.cq,.82);this.card.rotateZ(.05);this.card.updateMatrixWorld(true)}
applyTexture(tex,serial,url){if(this.disposed||serial!==this.serial||!this.face){tex.dispose();return}tex.colorSpace=THREE.SRGBColorSpace;tex.needsUpdate=true;const old=this.face.material;this.face.material=new THREE.MeshBasicMaterial({map:tex,side:THREE.DoubleSide,toneMapped:false,depthTest:false,depthWrite:false});this.face.renderOrder=100;disposeMaterial(old);Object.assign(this.canvas.dataset,{puppetCardTexture:'ready',puppetCardUrl:url,puppetCardError:''})}
loadTexture(cs,serial,i=0){if(serial!==this.serial||this.disposed)return;if(i>=cs.length){this.canvas.dataset.puppetCardTexture='failed';this.canvas.dataset.puppetCardError='all-card-texture-candidates-failed';return}const url=cs[i];this.canvas.dataset.puppetCardUrl=url;this.canvas.dataset.puppetCardTexture=i?'loading-fallback':'loading';new THREE.TextureLoader().load(url,t=>this.applyTexture(t,serial,url),undefined,e=>{if(serial!==this.serial||this.disposed)return;this.canvas.dataset.puppetCardError=String(e?.message||e||`texture-failed-${i}`);this.loadTexture(cs,serial,i+1)})}
attachCard(){if(!this.model)return;this.createCard();this.updateCard();const c=this.selectedCard||pendingCard,cs=candidates(c),serial=++this.serial;Object.assign(this.canvas.dataset,{puppetCardId:c?.cardId||'',puppetCardSource:cardPath(c),puppetCardCandidates:cs.join('|')});if(!cs.length){this.canvas.dataset.puppetCardTexture='fallback';return}this.loadTexture(cs,serial)}
setCard(id,path){this.selectedCard={cardId:String(id||''),imagePath:String(path||'')};suppressLegacyPreview();if(this.model)this.attachCard()}
resize(){const r=stageRect();Object.assign(this.canvas.style,{left:`${r.left}px`,top:`${r.top}px`,width:`${r.width}px`,height:`${r.height}px`});this.renderer.setSize(Math.max(r.width,1),Math.max(r.height,1),false);this.camera.aspect=r.width/Math.max(r.height,1);this.camera.fov=r.width<560?38:34;this.camera.updateProjectionMatrix();this.fit();this.updateCard()}
contains(e){const r=this.canvas.getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom}
cardHit(e){if(!this.face||!this.contains(e))return false;this.updateCard();const r=this.canvas.getBoundingClientRect();this.ndc.set((e.clientX-r.left)/Math.max(r.width,1)*2-1,-((e.clientY-r.top)/Math.max(r.height,1)*2-1));this.ray.setFromCamera(this.ndc,this.camera);return this.ray.intersectObject(this.face,false).length>0}
returnBrowse(){const id=this.selectedCard?.cardId||pendingCard?.cardId;if(!id)return;this.canvas.dataset.puppetCardAction='return-to-browse';location.hash=browseHash(id)}
target(e){if(!this.bones)return{kind:'body'};const r=this.canvas.getBoundingClientRect(),x=clamp((e.clientX-r.left)/Math.max(r.width,1),0,1),y=clamp((e.clientY-r.top)/Math.max(r.height,1),0,1),b=this.bones;if(y<.2&&x>.32&&x<.68&&b.head)return{kind:'head',bone:b.head};if(y>=.18&&y<.48&&x<.42&&b.leftUpperArm)return{kind:'leftArm',bone:b.leftUpperArm,secondary:b.leftForeArm};if(y>=.18&&y<.48&&x>.58&&b.rightUpperArm)return{kind:'rightArm',bone:b.rightUpperArm,secondary:b.rightForeArm};if(y>=.34&&y<.56&&x<.46&&b.leftHand)return{kind:'leftHand',bone:b.leftHand};if(y>=.34&&y<.56&&x>.54&&b.rightHand)return{kind:'rightHand',bone:b.rightHand};if(y>=.5&&y<.79&&x<.5&&b.leftUpperLeg)return{kind:'leftLeg',bone:b.leftUpperLeg,secondary:b.leftLowerLeg};if(y>=.5&&y<.79&&x>=.5&&b.rightUpperLeg)return{kind:'rightLeg',bone:b.rightUpperLeg,secondary:b.rightLowerLeg};if(y>=.78&&x<.5&&(b.leftFoot||b.leftLowerLeg))return{kind:'leftFoot',bone:b.leftFoot||b.leftLowerLeg};if(y>=.78&&x>=.5&&(b.rightFoot||b.rightLowerLeg))return{kind:'rightFoot',bone:b.rightFoot||b.rightLowerLeg};if(y>=.2&&y<.55&&b.chest)return{kind:'torso',bone:b.chest};return{kind:'body'}}
refresh(){this.canvas.dataset.puppetTargets=[...this.drags.values()].map(d=>d.kind).join('|')}
pointerDown(e){if(!this.model||e.button>0||!this.contains(e)||uiTarget(e.target)||e.clientY<92)return;if(this.cardHit(e)){this.drags.set(e.pointerId,{startX:e.clientX,startY:e.clientY,kind:'card',moved:false});this.refresh();return}const t=this.target(e);if([...this.drags.values()].some(d=>d.kind===t.kind&&t.kind!=='body'))return;this.drags.set(e.pointerId,{startX:e.clientX,startY:e.clientY,kind:t.kind,bone:t.bone,secondary:t.secondary,boneRot:t.bone?.rotation.clone()||null,secondaryRot:t.secondary?.rotation.clone()||null,bodyY:this.pivot.rotation.y,bodyX:this.pivot.rotation.x});this.refresh()}
pointerMove(e){const d=this.drags.get(e.pointerId);if(!d)return;if(e.cancelable)e.preventDefault();if(d.kind==='card'){if(Math.hypot(e.clientX-d.startX,e.clientY-d.startY)>10)d.moved=true;return}const r=this.canvas.getBoundingClientRect(),dx=(e.clientX-d.startX)/Math.max(r.width,1),dy=(e.clientY-d.startY)/Math.max(r.height,1),s=Math.PI*1.45;if(d.kind==='body'){this.pivot.rotation.y=d.bodyY+dx*Math.PI*2;this.pivot.rotation.x=d.bodyX+clamp(dy*Math.PI*.55,-.65,.65);return}if(!d.bone)return;d.bone.rotation.copy(d.boneRot);if(d.kind==='head'){d.bone.rotation.y+=clamp(dx*s,-.9,.9);d.bone.rotation.x+=clamp(dy*s,-.55,.55);return}if(d.kind==='torso'){d.bone.rotation.y+=clamp(dx*s*.8,-.8,.8);d.bone.rotation.z+=clamp(-dy*s*.45,-.5,.5);return}if(['leftHand','rightHand','leftFoot','rightFoot'].includes(d.kind)){d.bone.rotation.y+=clamp(dx*s,-1,1);d.bone.rotation.x+=clamp(dy*s,-.8,.8);d.bone.rotation.z+=clamp(dx*s*.35,-.45,.45);return}const left=d.kind==='leftArm'||d.kind==='leftLeg',side=left?1:-1;d.bone.rotation.z+=side*clamp(-dy*s,-1.25,1.25);d.bone.rotation.x+=clamp(dx*s*.78,-1,1);d.bone.rotation.y+=side*clamp(dx*s*.3,-.45,.45);if(d.secondary&&d.secondaryRot){d.secondary.rotation.copy(d.secondaryRot);d.secondary.rotation.x+=clamp(-dy*s*.55,-.9,.9);d.secondary.rotation.z+=side*clamp(dx*s*.38,-.55,.55)}}
pointerUp(e){const d=this.drags.get(e.pointerId);if(!d)return;this.drags.delete(e.pointerId);this.refresh();if(d.kind==='card'&&!d.moved)this.returnBrowse()}
reset(){this.drags.clear();for(const[b,r]of this.rest)b.rotation.copy(r);this.pivot.rotation.set(0,MODEL_FACING_Y,0);this.pivot.position.set(0,0,0);this.updateCard();this.refresh()}
tick=()=>{if(this.disposed||document.hidden)return;suppressLegacyPreview();this.updateCard();this.renderer.render(this.scene,this.camera);this.frame=requestAnimationFrame(this.tick)};
resume(){if(!this.disposed&&!this.frame&&!document.hidden)this.frame=requestAnimationFrame(this.tick)}
dispose(){this.disposed=true;this.serial++;if(this.frame)cancelAnimationFrame(this.frame);removeEventListener('resize',this.onResize);removeEventListener('orientationchange',this.onResize);removeEventListener('pointerdown',this.onDown,true);removeEventListener('pointermove',this.onMove,true);removeEventListener('pointerup',this.onUp,true);removeEventListener('pointercancel',this.onUp,true);this.mixer?.stopAllAction();disposeObject(this.card);disposeObject(this.model);this.renderer.dispose();this.canvas.remove()}}
function enable(){if(puppet)return;setLegacyVisible(false);suppressLegacyPreview();puppet=new TranscriptionPuppet}
function disable(){puppet?.dispose();puppet=null;setLegacyVisible(false);suppressLegacyPreview()}
window.transcriptionPuppetSetEnabled=e=>Boolean(e)?enable():disable();window.transcriptionPuppetSetCard=(id,path)=>{pendingCard={cardId:String(id||''),imagePath:String(path||'')};puppet?.setCard(pendingCard.cardId,pendingCard.imagePath)};window.transcriptionPuppetReset=()=>puppet?.reset();addEventListener('pagehide',()=>{if(puppet)disable()});